const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const C=require('./core.cjs'),S=require('./season-core.cjs'),R=require('./season.cjs');
function input(){return {version:1,drama_id:'example',sources:[{id:'official',name:'Official episode information',url:'https://example.org/episode',extract:'The official source describes a journey.'}],records:[{id:'collection-1',kind:'season',imported_facts:{name:'Example',url:'/drama/example/season-1'},existing:{},verified_facts:{season:1},source_ids:['official']},{id:'collection-1-episode-1',kind:'episode',imported_facts:{name:'Example',episode:1},existing:{},verified_facts:{season:1,episode:1},source_ids:['official']}]};}
function exported(){const p=input();return {project:'abcdefghijklmnopqrst',scope:{drama:'example',collection:'collection-1',season:1},input:p,snapshot:p.records.map((r,i)=>({target_id:r.id,kind:i?'episode_group':'collection',uuid:i?'22222222-2222-4222-8222-222222222222':'11111111-1111-4111-8111-111111111111',identity:i?{status:'published',episode:1,broadcast:null,part:null,collection:'collection-1'}:{status:'published',seasons:[1],edition:'subtitled',drama:'example'},editorial:null}))};}
function plan(){const e=exported(),items=e.input.records.map(S.metadata),requests=items.map((i,n)=>({action:'update_metadata',targetType:n?'episode_group':'collection',targetId:i.id,payload:S.payload(i,e.input.sources)}));const p={version:1,...e,items,requests,review:[]};p.hash=S.planHash(p);return p;}
function temp(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'season-pipeline-'));return {dir,cleanup(){const resolved=path.resolve(dir);if(path.dirname(resolved)!==path.resolve(os.tmpdir())||!path.basename(resolved).startsWith('season-pipeline-'))throw Error('Unsafe test cleanup');fs.rmSync(resolved,{recursive:true,force:true});}};}
test('duplicate episode identities stop before AI and produce an actionable report',async()=>{const t=temp();try{const e=exported(),duplicate=structuredClone(e.input.records[1]);duplicate.id='collection-1-bolum-28';e.input.records.push(duplicate);await assert.rejects(R.run({out:t.dir,ai:true},{exporter:async()=>e,gemma:async()=>{throw Error('AI must not run');}}),/Catalog numbering conflict.*collection-1-episode-1 and collection-1-bolum-28/);const report=JSON.parse(fs.readFileSync(path.join(t.dir,'identity-review.json')));assert.equal(report.conflicts.length,1);assert.equal(report.publication,'not applied');assert.ok(!fs.existsSync(path.join(t.dir,'plan.json')));assert.ok(!fs.existsSync(path.join(t.dir,'.season.lock')));}finally{t.cleanup();}});
test('deterministic metadata preserves verified numbers and omits imported broadcast/languages',()=>{const r=input().records[1];r.imported_facts.broadcast=99;r.imported_facts.languages=['Urdu'];const i=S.metadata(r);assert.match(i.seo_title,/Episode 1/);assert.doesNotMatch(i.seo_title,/Bolum|Urdu/);r.verified_facts.broadcast=99;r.verified_facts.languages=['Urdu'];r.verified_facts.edition='subtitled';assert.match(S.metadata(r).seo_title,/Bolum 99/);assert.ok(S.metadata(r).seo_title.length<=60);assert.ok(S.metadata(r).seo_description.length<=160);});
test('long names require an explicit alias without dropping identity',()=>{const r=input().records[1];r.imported_facts.name='Long '.repeat(18);assert.throws(()=>S.metadata(r),/approved_short_name/);r.verified_facts.approved_short_name='Example';assert.match(S.metadata(r).seo_title,/S1 E1/);});
test('evidence cannot cross dramas, editions or local numbering',()=>{const p=input(),e=structuredClone(p);e.drama_id='other';assert.throws(()=>R.mergeEvidence(p,e),/drama/);e.drama_id=p.drama_id;e.records[1].id='other-edition';assert.throws(()=>R.mergeEvidence(p,e),/edition/);e.records[1].id=p.records[1].id;e.records[1].verified_facts.episode=2;assert.throws(()=>R.mergeEvidence(p,e),/conflicts/);});
test('content must preserve record coverage, citations and language evidence',()=>{const batch=input(),base=batch.records.map(S.metadata);const reply={items:batch.records.map(r=>({id:r.id,sections:[{heading:'Context',content:'The official source describes a journey.',source_ids:['official']}]}))};assert.equal(S.addContent(base,batch,reply).length,2);reply.items.pop();assert.throws(()=>S.addContent(base,batch,reply),/Missing/);reply.items.push({id:batch.records[1].id,sections:[{heading:'Context',content:'English subtitles are available.',source_ids:['official']}]});assert.throws(()=>S.addContent(base,batch,reply),/language/);reply.items[1].sections[0].source_ids=['invented'];assert.throws(()=>S.addContent(base,batch,reply),/citation/);});
test('promotional previews require an explicit file-match disclosure',()=>{const p=input();p.sources[0].name='Official promotional preview';const base=p.records.map(S.metadata),reply={items:p.records.map(r=>({id:r.id,sections:[{heading:'Summary',content:'A journey.',source_ids:['official']}]}))};assert.throws(()=>S.addContent(base,p,reply),/disclosure/);for(const i of reply.items){i.sections[0].heading='Official broadcast preview (file match unconfirmed)';i.sections[0].content='The official preview describes a journey; publisher-file matching remains unconfirmed.';}assert.equal(S.addContent(base,p,reply).length,2);});
test('changed plans and mismatched payloads cannot be exported for apply',()=>{const p=plan();S.assertPlan(p);p.requests[0].payload.seo_title='Changed';assert.throws(()=>S.assertPlan(p),/hash/);p.hash=S.planHash(p);assert.throws(()=>S.assertPlan(p),/Payload/);});
test('SQL scopes writes and checks inventory, numbering and previous editorial under locks',()=>{const sql=S.applySQL(plan());assert.match(sql,/lock table public.published_editorial/);assert.match(sql,/actual_identity is distinct/);assert.match(sql,/Stale target/);assert.match(sql,/Season inventory changed/);assert.match(sql,/Collection\/drama identity changed/);assert.match(sql,/begin;/);assert.match(sql,/commit;$/);});
test('readback compares nested JSON without depending on object key order',()=>{const p=plan();const rows=p.requests.map(r=>({target_id:r.targetId,editorial:{seo_title:r.payload.seo_title,approved_display_title:r.payload.label,seo_description:r.payload.seo_description,structured_article:r.payload.structured_article,short_description:r.payload.short_description}}));S.verifyReadback(p,rows);rows[1].editorial.seo_title='wrong';assert.throws(()=>S.verifyReadback(p,rows),/mismatch/);assert.throws(()=>S.verifyReadback(p,rows.slice(0,1)),/count/);});
test('orchestrator resumes accepted content without calling AI again',async()=>{const t=temp();try{const evidence=path.join(t.dir,'evidence.json');fs.writeFileSync(evidence,JSON.stringify(input()));let calls=0;const gemma=async(prompt,options)=>{options.onAttempt();calls++;const p=JSON.parse(prompt);return {text:JSON.stringify({items:p.input.records.map(r=>({id:r.id,sections:[{heading:'Official context',content:'The official source describes a journey.',source_ids:['official']}]}))}),usage:{totalTokenCount:123}};};const args={drama:'example',season:'1',collection:'collection-1',out:t.dir,evidence,ai:true};await R.run(args,{exporter:async()=>exported(),gemma});await R.run(args,{exporter:async()=>exported(),gemma:async()=>{throw Error('Resume must not call AI');}});assert.equal(calls,1);const p=JSON.parse(fs.readFileSync(path.join(t.dir,'plan.json')));assert.equal(p.api_requests,0);assert.equal(p.items[0].sections.length,1);S.assertPlan(p);}finally{t.cleanup();}});
test('one failed content batch does not prevent later batches or metadata delivery',async()=>{const t=temp();try{const evidence=path.join(t.dir,'evidence.json');fs.writeFileSync(evidence,JSON.stringify(input()));let calls=0;await R.run({drama:'example',season:'1',collection:'collection-1',out:t.dir,evidence,ai:true,'batch-size':'1'},{exporter:async()=>exported(),gemma:async(prompt,options)=>{options.onAttempt();calls++;if(calls===1)throw Error('Google API HTTP 500');const r=JSON.parse(prompt).input.records[0];return {text:JSON.stringify({items:[{id:r.id,sections:[{heading:'Context',content:'The official source describes a journey.',source_ids:['official']}]}]}),usage:{totalTokenCount:10}};}});const p=JSON.parse(fs.readFileSync(path.join(t.dir,'plan.json')));assert.equal(p.requests.length,2);assert.equal(p.items[1].sections.length,1);assert.ok(p.review[0].flags.some(f=>f.includes('pending')));}finally{t.cleanup();}});
test('retry attempts consume the budget and provider bodies stay redacted',async()=>{const old=global.fetch,key=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='private-test';let calls=0,attempts=0;global.fetch=async()=>{calls++;return new Response('private-test',{status:500});};try{await assert.rejects(C.callGemma('test',{attempts:3,onAttempt(){if(attempts>=1)throw Error('Request budget reached');attempts++;}}),/budget/);assert.equal(calls,1);}finally{global.fetch=old;if(key===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=key;}});
test('transient provider failures recover within bounded retries',async()=>{const old=global.fetch,key=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='mock-private';let attempts=0;global.fetch=async()=>{attempts++;return attempts===1?new Response('private provider body',{status:500}):new Response(JSON.stringify({candidates:[{finishReason:'STOP',content:{parts:[{text:'{"items":[]}' }]}}]}),{status:200});};try{const result=await C.callGemma('test',{attempts:2});assert.equal(attempts,2);assert.equal(result.text,'{"items":[]}');}finally{global.fetch=old;if(key===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=key;}});
test('apply saves backup, verifies records and exports guarded rollback',async()=>{
 const t=temp(),oldFetch=global.fetch,oldURL=process.env.NEXT_PUBLIC_SUPABASE_URL,oldToken=process.env.SUPABASE_ACCESS_TOKEN;
 process.env.NEXT_PUBLIC_SUPABASE_URL='https://abcdefghijklmnopqrst.supabase.co';process.env.SUPABASE_ACCESS_TOKEN='mock-management-token';
 try{
  const p=plan();C.writeJSON(path.join(t.dir,'plan.json'),p);C.writeJSON(path.join(t.dir,'approval.json'),{hash:p.hash,reviewer:'Test reviewer'});
  const after=p.snapshot.map((s,i)=>({...s,editorial:{id:s.uuid,collection_id:s.kind==='collection'?s.uuid:null,group_id:s.kind==='episode_group'?s.uuid:null,locale:'en',approved_display_title:p.requests[i].payload.label,short_description:p.requests[i].payload.short_description,seo_title:p.requests[i].payload.seo_title,seo_description:p.requests[i].payload.seo_description,structured_article:p.requests[i].payload.structured_article,published_at:'2026-10-04T00:00:00Z',updated_at:'2026-10-04T00:00:00Z'}}));
  let calls=0;global.fetch=async(url,opts)=>{assert.match(url,/^https:\/\/api.supabase.com\/v1\/projects\/abcdefghijklmnopqrst\/database\/query$/);const body=JSON.parse(opts.body);calls++;if(calls===1){assert.equal(body.read_only,true);return new Response(JSON.stringify(p.snapshot),{status:201});}if(calls===2){assert.equal(body.read_only,false);assert.match(body.query,/Stale target/);return new Response('[]',{status:201});}assert.equal(body.read_only,true);return new Response(JSON.stringify(after),{status:201});};
  await R.main(['apply','--out',t.dir,'--hash',p.hash]);assert.equal(calls,3);assert.ok(fs.existsSync(path.join(t.dir,'database-backup.json')));assert.equal(JSON.parse(fs.readFileSync(path.join(t.dir,'apply-receipt.json'))).applied,2);const rollback=fs.readFileSync(path.join(t.dir,'rollback.sql'),'utf8');assert.match(rollback,/Editorial changed after apply/);assert.match(rollback,/delete from public.published_editorial where id=/);await assert.rejects(R.main(['apply','--out',t.dir,'--hash',p.hash]),/already attempted/);assert.equal(calls,3);
 }finally{global.fetch=oldFetch;for(const [k,v]of [['NEXT_PUBLIC_SUPABASE_URL',oldURL],['SUPABASE_ACCESS_TOKEN',oldToken]])if(v===undefined)delete process.env[k];else process.env[k]=v;t.cleanup();}
});
test('an ambiguous database write failure is never automatically retried',async()=>{
 const t=temp(),oldFetch=global.fetch,oldURL=process.env.NEXT_PUBLIC_SUPABASE_URL,oldToken=process.env.SUPABASE_ACCESS_TOKEN;process.env.NEXT_PUBLIC_SUPABASE_URL='https://abcdefghijklmnopqrst.supabase.co';process.env.SUPABASE_ACCESS_TOKEN='mock-token';
 try{const p=plan();C.writeJSON(path.join(t.dir,'plan.json'),p);C.writeJSON(path.join(t.dir,'approval.json'),{hash:p.hash,reviewer:'Test'});let calls=0;global.fetch=async()=>{calls++;return calls===1?new Response(JSON.stringify(p.snapshot),{status:201}):new Response('mock-token',{status:500});};await assert.rejects(R.main(['apply','--out',t.dir,'--hash',p.hash]),e=>e.message.includes('verify state')&&!e.message.includes('mock-token'));assert.equal(calls,2);assert.ok(fs.existsSync(path.join(t.dir,'database-backup.json')));await assert.rejects(R.main(['apply','--out',t.dir,'--hash',p.hash]),/already attempted/);assert.equal(calls,2);}finally{global.fetch=oldFetch;for(const [k,v]of [['NEXT_PUBLIC_SUPABASE_URL',oldURL],['SUPABASE_ACCESS_TOKEN',oldToken]])if(v===undefined)delete process.env[k];else process.env[k]=v;t.cleanup();}
});
