INSERT INTO public.episode_groups (id, source_id, collection_id, label, reported_episode_number, bolum, part, order_key, content_type, status)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-84'),
      'collection-82-bolum-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      'Episode 1 · Bolum 84',
      1,
      84,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-88-bolum-84'),
      'collection-88-bolum-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-88'),
      'Episode 1 · Bolum 84',
      1,
      84,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-87-episode-1'),
      'collection-87-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-87'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-86-bolum-32'),
      'collection-86-bolum-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-86'),
      'Episode 1 · Bolum 32',
      1,
      32,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-84-episode-1'),
      'collection-84-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-84'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-83-bolum-185'),
      'collection-83-bolum-185',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-83'),
      'Episode 1 · Bolum 185',
      1,
      185,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-1'),
      'collection-78-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-149'),
      'collection-77-bolum-149',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 149 · Bolum 149',
      149,
      149,
      NULL,
      149,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-50'),
      'collection-76-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-1'),
      'collection-73-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-1'),
      'collection-72-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-29'),
      'collection-71-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-165'),
      'collection-70-episode-165',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 165',
      165,
      NULL,
      NULL,
      165,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-1'),
      'collection-69-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-1'),
      'collection-65-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-93'),
      'collection-63-episode-93',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 93',
      93,
      NULL,
      NULL,
      93,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-1'),
      'collection-61-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-68'),
      'collection-59-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-80'),
      'collection-57-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-1'),
      'collection-6-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-45'),
      'collection-5-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-1'),
      'collection-4-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-20'),
      'collection-3-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-1'),
      'collection-2-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-1'),
      'collection-56-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-34'),
      'collection-53-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-22'),
      'collection-52-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-1'),
      'collection-51-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-1'),
      'collection-49-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-1'),
      'collection-48-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-1'),
      'collection-47-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-1'),
      'collection-46-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-1'),
      'collection-43-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-1'),
      'collection-42-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-33'),
      'collection-41-bolum-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 1 · Bolum 33',
      1,
      33,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-49'),
      'collection-40-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-99'),
      'collection-38-bolum-99',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 1 · Bolum 99',
      1,
      99,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-1'),
      'collection-37-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-51'),
      'collection-36-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-1'),
      'collection-34-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-15'),
      'collection-33-episode-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 15',
      15,
      NULL,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-1'),
      'collection-32-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-13-part-1'),
      'collection-31-episode-13-part-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 13 · Part 1',
      13,
      NULL,
      1,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-1'),
      'collection-30-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-1'),
      'collection-28-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-1'),
      'collection-27-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-165'),
      'collection-26-episode-165',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 165',
      165,
      NULL,
      NULL,
      165,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-10'),
      'collection-25-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-12'),
      'collection-24-episode-12',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 12',
      12,
      NULL,
      NULL,
      12,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-1'),
      'collection-23-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-1'),
      'collection-22-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-1'),
      'collection-21-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-1'),
      'collection-20-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-19-episode-120'),
      'collection-19-episode-120',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-19'),
      'Episode 120',
      120,
      NULL,
      NULL,
      120,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-89'),
      'collection-18-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-55'),
      'collection-17-episode-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 55',
      55,
      NULL,
      NULL,
      55,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-18'),
      'collection-16-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-1'),
      'collection-11-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-1'),
      'collection-10-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-1'),
      'collection-8-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-1'),
      'collection-7-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-87-episode-2'),
      'collection-87-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-87'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-84-episode-2'),
      'collection-84-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-84'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-83-bolum-186'),
      'collection-83-bolum-186',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-83'),
      'Episode 2 · Bolum 186',
      2,
      186,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-150'),
      'collection-77-episode-150',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 150',
      150,
      NULL,
      NULL,
      150,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-51'),
      'collection-76-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-2'),
      'collection-73-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-113'),
      'collection-69-episode-113',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 113',
      113,
      NULL,
      NULL,
      113,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-2'),
      'collection-65-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-94'),
      'collection-63-episode-94',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 94',
      94,
      NULL,
      NULL,
      94,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-2'),
      'collection-61-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-69'),
      'collection-59-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-81'),
      'collection-57-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-2'),
      'collection-6-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-46'),
      'collection-5-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-2'),
      'collection-4-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-21'),
      'collection-3-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-10'),
      'collection-2-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-2'),
      'collection-56-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-35'),
      'collection-53-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-23'),
      'collection-52-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-2'),
      'collection-51-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-2'),
      'collection-49-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-2'),
      'collection-48-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-2'),
      'collection-47-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-2'),
      'collection-46-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-2'),
      'collection-43-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-2'),
      'collection-42-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-50'),
      'collection-40-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-2'),
      'collection-37-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-52'),
      'collection-36-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-2'),
      'collection-34-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-16'),
      'collection-33-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-2'),
      'collection-32-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-13-part-2'),
      'collection-31-episode-13-part-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 13 · Part 2',
      13,
      NULL,
      2,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-2'),
      'collection-30-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-2'),
      'collection-28-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-166'),
      'collection-26-episode-166',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 166',
      166,
      NULL,
      NULL,
      166,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-2'),
      'collection-23-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-2'),
      'collection-22-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-2'),
      'collection-21-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-2'),
      'collection-20-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-19-episode-121'),
      'collection-19-episode-121',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-19'),
      'Episode 121',
      121,
      NULL,
      NULL,
      121,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-90'),
      'collection-18-episode-90',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 90',
      90,
      NULL,
      NULL,
      90,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-56'),
      'collection-17-episode-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 56',
      56,
      NULL,
      NULL,
      56,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-19'),
      'collection-16-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-2'),
      'collection-11-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-2'),
      'collection-10-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-2'),
      'collection-8-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-2'),
      'collection-7-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-85'),
      'collection-82-bolum-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      'Episode 2 · Bolum 85',
      2,
      85,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-2'),
      'collection-78-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-151'),
      'collection-77-episode-151',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 151',
      151,
      NULL,
      NULL,
      151,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-52'),
      'collection-76-bolum-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 52 · Bolum 52',
      52,
      52,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-3'),
      'collection-73-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-2'),
      'collection-72-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-30'),
      'collection-71-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-166'),
      'collection-70-episode-166',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 166',
      166,
      NULL,
      NULL,
      166,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-114'),
      'collection-69-episode-114',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 114',
      114,
      NULL,
      NULL,
      114,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-3'),
      'collection-65-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-95'),
      'collection-63-episode-95',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 95',
      95,
      NULL,
      NULL,
      95,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-3'),
      'collection-61-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-70'),
      'collection-59-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-82'),
      'collection-57-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-3'),
      'collection-6-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-47'),
      'collection-5-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-3'),
      'collection-4-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-22'),
      'collection-3-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-11'),
      'collection-2-episode-11',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 11',
      11,
      NULL,
      NULL,
      11,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-3'),
      'collection-56-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-36'),
      'collection-53-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-24'),
      'collection-52-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-3'),
      'collection-51-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-3'),
      'collection-49-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-3'),
      'collection-48-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-3'),
      'collection-47-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-3'),
      'collection-46-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-3'),
      'collection-43-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-3'),
      'collection-42-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-34'),
      'collection-41-bolum-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 2 · Bolum 34',
      2,
      34,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-51'),
      'collection-40-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-100'),
      'collection-38-bolum-100',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 2 · Bolum 100',
      2,
      100,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-3'),
      'collection-37-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-53'),
      'collection-36-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-3'),
      'collection-34-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-17'),
      'collection-33-episode-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 17',
      17,
      NULL,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-3'),
      'collection-32-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-14-part-1'),
      'collection-31-episode-14-part-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 14 · Part 1',
      14,
      NULL,
      1,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-3'),
      'collection-30-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-3'),
      'collection-28-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-2'),
      'collection-27-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-167'),
      'collection-26-episode-167',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 167',
      167,
      NULL,
      NULL,
      167,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-11'),
      'collection-25-episode-11',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 11',
      11,
      NULL,
      NULL,
      11,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-13'),
      'collection-24-episode-13',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 13',
      13,
      NULL,
      NULL,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-3'),
      'collection-23-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-3'),
      'collection-22-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-3'),
      'collection-21-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-3'),
      'collection-20-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-91'),
      'collection-18-episode-91',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 91',
      91,
      NULL,
      NULL,
      91,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-57'),
      'collection-17-episode-57',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 57',
      57,
      NULL,
      NULL,
      57,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-20'),
      'collection-16-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-3'),
      'collection-11-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-3'),
      'collection-10-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-3'),
      'collection-8-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-3'),
      'collection-7-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-86'),
      'collection-82-bolum-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      'Episode 3 · Bolum 86',
      3,
      86,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-152'),
      'collection-77-episode-152',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 152',
      152,
      NULL,
      NULL,
      152,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-52'),
      'collection-76-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-4'),
      'collection-73-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-3'),
      'collection-72-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-115'),
      'collection-69-episode-115',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 115',
      115,
      NULL,
      NULL,
      115,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-4'),
      'collection-65-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-96'),
      'collection-63-episode-96',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 96',
      96,
      NULL,
      NULL,
      96,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-4'),
      'collection-61-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-71'),
      'collection-59-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-83'),
      'collection-57-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-4'),
      'collection-6-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-48'),
      'collection-5-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-4'),
      'collection-4-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-23'),
      'collection-3-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-12'),
      'collection-2-episode-12',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 12',
      12,
      NULL,
      NULL,
      12,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-4'),
      'collection-56-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-37'),
      'collection-53-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-25'),
      'collection-52-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-4'),
      'collection-51-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-4'),
      'collection-49-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-4'),
      'collection-48-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-4'),
      'collection-47-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-4'),
      'collection-46-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-4'),
      'collection-43-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-4'),
      'collection-42-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-52'),
      'collection-40-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-4'),
      'collection-37-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-54'),
      'collection-36-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-4'),
      'collection-34-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-18'),
      'collection-33-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-4'),
      'collection-32-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-14-part-2'),
      'collection-31-episode-14-part-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 14 · Part 2',
      14,
      NULL,
      2,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-4'),
      'collection-30-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-4'),
      'collection-28-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-168'),
      'collection-26-episode-168',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 168',
      168,
      NULL,
      NULL,
      168,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-4'),
      'collection-23-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-4'),
      'collection-22-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-4'),
      'collection-21-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-4'),
      'collection-20-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-92'),
      'collection-18-episode-92',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 92',
      92,
      NULL,
      NULL,
      92,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-58'),
      'collection-17-episode-58',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 58',
      58,
      NULL,
      NULL,
      58,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-21'),
      'collection-16-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-4'),
      'collection-11-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-4'),
      'collection-10-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-4'),
      'collection-8-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-4'),
      'collection-7-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-3'),
      'collection-78-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-153'),
      'collection-77-episode-153',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 153',
      153,
      NULL,
      NULL,
      153,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-53'),
      'collection-76-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-5'),
      'collection-73-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-4'),
      'collection-72-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-31'),
      'collection-71-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-167'),
      'collection-70-episode-167',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 167',
      167,
      NULL,
      NULL,
      167,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-116'),
      'collection-69-episode-116',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 116',
      116,
      NULL,
      NULL,
      116,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-5'),
      'collection-65-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-97'),
      'collection-63-episode-97',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 97',
      97,
      NULL,
      NULL,
      97,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-5'),
      'collection-61-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-72'),
      'collection-59-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-84'),
      'collection-57-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-5'),
      'collection-6-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-49'),
      'collection-5-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-5'),
      'collection-4-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-24'),
      'collection-3-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-13'),
      'collection-2-episode-13',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 13',
      13,
      NULL,
      NULL,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-5'),
      'collection-56-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-38'),
      'collection-53-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-26'),
      'collection-52-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-5'),
      'collection-51-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-5'),
      'collection-49-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-5'),
      'collection-48-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-5'),
      'collection-47-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-5'),
      'collection-46-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-5'),
      'collection-43-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-5'),
      'collection-42-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-35'),
      'collection-41-bolum-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 3 · Bolum 35',
      3,
      35,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-53'),
      'collection-40-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-101'),
      'collection-38-bolum-101',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 3 · Bolum 101',
      3,
      101,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-5'),
      'collection-37-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-55'),
      'collection-36-episode-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 55',
      55,
      NULL,
      NULL,
      55,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-5'),
      'collection-34-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-19'),
      'collection-33-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-5'),
      'collection-32-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-15-part-2'),
      'collection-31-episode-15-part-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 15 · Part 2',
      15,
      NULL,
      2,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-5'),
      'collection-30-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    )
ON CONFLICT (source_id) DO UPDATE SET
  label = CASE WHEN episode_groups.updated_at > episode_groups.created_at THEN episode_groups.label ELSE EXCLUDED.label END,
  reported_episode_number = EXCLUDED.reported_episode_number,
  bolum = EXCLUDED.bolum,
  part = EXCLUDED.part,
  order_key = EXCLUDED.order_key,
  status = CASE WHEN episode_groups.source_id LIKE 'collection-68%' THEN 'published' ELSE episode_groups.status END,
  updated_at = now();