INSERT INTO public.episode_groups (id, source_id, collection_id, label, reported_episode_number, bolum, part, order_key, content_type, status)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-5'),
      'collection-28-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-3'),
      'collection-27-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-169'),
      'collection-26-episode-169',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 169',
      169,
      NULL,
      NULL,
      169,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-12'),
      'collection-25-episode-12',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 12',
      12,
      NULL,
      NULL,
      12,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-14'),
      'collection-24-episode-14',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 14',
      14,
      NULL,
      NULL,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-5'),
      'collection-23-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-5'),
      'collection-22-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-5'),
      'collection-21-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-5'),
      'collection-20-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-93'),
      'collection-18-episode-93',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 93',
      93,
      NULL,
      NULL,
      93,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-59'),
      'collection-17-episode-59',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 59',
      59,
      NULL,
      NULL,
      59,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-22'),
      'collection-16-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-5'),
      'collection-11-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-5'),
      'collection-10-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-5'),
      'collection-8-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-5'),
      'collection-7-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-154'),
      'collection-77-episode-154',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 154',
      154,
      NULL,
      NULL,
      154,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-6'),
      'collection-73-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-5'),
      'collection-72-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-117'),
      'collection-69-episode-117',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 117',
      117,
      NULL,
      NULL,
      117,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-6'),
      'collection-65-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-98'),
      'collection-63-episode-98',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 98',
      98,
      NULL,
      NULL,
      98,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-6'),
      'collection-61-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-73'),
      'collection-59-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-131'),
      'collection-50-episode-131',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 131',
      131,
      NULL,
      NULL,
      131,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-85'),
      'collection-57-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-6'),
      'collection-6-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-50'),
      'collection-5-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-6'),
      'collection-4-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-25'),
      'collection-3-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-14'),
      'collection-2-episode-14',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 14',
      14,
      NULL,
      NULL,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-6'),
      'collection-56-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-39'),
      'collection-53-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-27'),
      'collection-52-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-6'),
      'collection-51-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-6'),
      'collection-49-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-6'),
      'collection-48-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-6'),
      'collection-47-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-6'),
      'collection-46-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-6'),
      'collection-43-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-6'),
      'collection-42-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-54'),
      'collection-40-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-6'),
      'collection-37-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-56'),
      'collection-36-episode-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 56',
      56,
      NULL,
      NULL,
      56,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-6'),
      'collection-34-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-20'),
      'collection-33-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-6'),
      'collection-32-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-6'),
      'collection-30-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-6'),
      'collection-28-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-1'),
      'collection-26-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-6'),
      'collection-23-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-6'),
      'collection-22-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-6'),
      'collection-21-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-6'),
      'collection-20-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-94'),
      'collection-18-episode-94',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 94',
      94,
      NULL,
      NULL,
      94,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-60'),
      'collection-17-episode-60',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 60',
      60,
      NULL,
      NULL,
      60,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-23'),
      'collection-16-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-6'),
      'collection-11-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-6'),
      'collection-10-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-6'),
      'collection-8-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-6'),
      'collection-7-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-4'),
      'collection-78-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-155'),
      'collection-77-episode-155',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 155',
      155,
      NULL,
      NULL,
      155,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-54'),
      'collection-76-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-7'),
      'collection-73-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-6'),
      'collection-72-episode-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 6',
      6,
      NULL,
      NULL,
      6,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-32'),
      'collection-71-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-168'),
      'collection-70-episode-168',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 168',
      168,
      NULL,
      NULL,
      168,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-118'),
      'collection-69-episode-118',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 118',
      118,
      NULL,
      NULL,
      118,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-7'),
      'collection-65-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-99'),
      'collection-63-episode-99',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 99',
      99,
      NULL,
      NULL,
      99,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-7'),
      'collection-61-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-74'),
      'collection-59-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-131'),
      'collection-50-bolum-131',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Bolum 131',
      NULL,
      131,
      NULL,
      131,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-86'),
      'collection-57-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-7'),
      'collection-6-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-51'),
      'collection-5-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-7'),
      'collection-4-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-26'),
      'collection-3-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-15'),
      'collection-2-episode-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 15',
      15,
      NULL,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-7'),
      'collection-56-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-40'),
      'collection-53-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-28'),
      'collection-52-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-7'),
      'collection-51-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-7'),
      'collection-48-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-7'),
      'collection-47-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-7'),
      'collection-46-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-7'),
      'collection-43-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-7'),
      'collection-42-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-36'),
      'collection-41-bolum-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 4 · Bolum 36',
      4,
      36,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-55'),
      'collection-40-episode-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 55',
      55,
      NULL,
      NULL,
      55,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-102'),
      'collection-38-bolum-102',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 4 · Bolum 102',
      4,
      102,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-7'),
      'collection-37-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-57'),
      'collection-36-episode-57',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 57',
      57,
      NULL,
      NULL,
      57,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-7'),
      'collection-34-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-21'),
      'collection-33-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-7'),
      'collection-32-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-16'),
      'collection-31-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-7'),
      'collection-30-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-7'),
      'collection-28-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-4'),
      'collection-27-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-2'),
      'collection-26-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-13'),
      'collection-25-episode-13',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 13',
      13,
      NULL,
      NULL,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-15'),
      'collection-24-episode-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 15',
      15,
      NULL,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-7'),
      'collection-23-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-7'),
      'collection-22-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-7'),
      'collection-21-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-7'),
      'collection-20-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-95'),
      'collection-18-episode-95',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 95',
      95,
      NULL,
      NULL,
      95,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-61'),
      'collection-17-episode-61',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 61',
      61,
      NULL,
      NULL,
      61,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-24'),
      'collection-16-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-7'),
      'collection-11-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-7'),
      'collection-10-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-7'),
      'collection-8-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-7'),
      'collection-7-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-156'),
      'collection-77-episode-156',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 156',
      156,
      NULL,
      NULL,
      156,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-8'),
      'collection-73-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-7'),
      'collection-72-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-119'),
      'collection-69-episode-119',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 119',
      119,
      NULL,
      NULL,
      119,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-8'),
      'collection-65-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-100'),
      'collection-63-episode-100',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 100',
      100,
      NULL,
      NULL,
      100,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-8'),
      'collection-61-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-75'),
      'collection-59-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-132'),
      'collection-50-bolum-132',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Bolum 132',
      NULL,
      132,
      NULL,
      132,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-87'),
      'collection-57-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-8'),
      'collection-6-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-52'),
      'collection-5-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-8'),
      'collection-4-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-27'),
      'collection-3-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-16'),
      'collection-2-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-8'),
      'collection-56-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-41'),
      'collection-53-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-29'),
      'collection-52-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-8'),
      'collection-51-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-8'),
      'collection-48-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-8'),
      'collection-47-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-8'),
      'collection-46-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-8'),
      'collection-43-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-8'),
      'collection-42-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-56'),
      'collection-40-episode-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 56',
      56,
      NULL,
      NULL,
      56,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-8'),
      'collection-37-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-58'),
      'collection-36-episode-58',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 58',
      58,
      NULL,
      NULL,
      58,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-8'),
      'collection-34-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-22'),
      'collection-33-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-8'),
      'collection-32-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-17'),
      'collection-31-episode-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 17',
      17,
      NULL,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-8'),
      'collection-30-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-8'),
      'collection-28-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-3'),
      'collection-26-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-8'),
      'collection-23-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-8'),
      'collection-22-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-8'),
      'collection-21-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-8'),
      'collection-20-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-96'),
      'collection-18-episode-96',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 96',
      96,
      NULL,
      NULL,
      96,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-62'),
      'collection-17-episode-62',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 62',
      62,
      NULL,
      NULL,
      62,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-25'),
      'collection-16-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-8'),
      'collection-11-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-8'),
      'collection-10-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-8'),
      'collection-8-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-8'),
      'collection-7-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-5'),
      'collection-78-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-157'),
      'collection-77-episode-157',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 157',
      157,
      NULL,
      NULL,
      157,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-55'),
      'collection-76-episode-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 55',
      55,
      NULL,
      NULL,
      55,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-9'),
      'collection-73-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-8'),
      'collection-72-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-33'),
      'collection-71-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-169'),
      'collection-70-episode-169',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 169',
      169,
      NULL,
      NULL,
      169,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-120'),
      'collection-69-episode-120',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 120',
      120,
      NULL,
      NULL,
      120,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-9'),
      'collection-65-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-101'),
      'collection-63-episode-101',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 101',
      101,
      NULL,
      NULL,
      101,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-9'),
      'collection-61-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-76'),
      'collection-59-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-88'),
      'collection-57-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-9'),
      'collection-6-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-53'),
      'collection-5-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-9'),
      'collection-4-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-28'),
      'collection-3-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-17'),
      'collection-2-episode-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 17',
      17,
      NULL,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-9'),
      'collection-56-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-42'),
      'collection-53-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-30'),
      'collection-52-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-9'),
      'collection-51-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-9'),
      'collection-48-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-9'),
      'collection-47-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-9'),
      'collection-46-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-9'),
      'collection-43-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-9'),
      'collection-42-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-37'),
      'collection-41-bolum-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 5 · Bolum 37',
      5,
      37,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-57'),
      'collection-40-episode-57',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 57',
      57,
      NULL,
      NULL,
      57,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-103'),
      'collection-38-bolum-103',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 5 · Bolum 103',
      5,
      103,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-9'),
      'collection-37-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-59'),
      'collection-36-episode-59',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 59',
      59,
      NULL,
      NULL,
      59,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-9'),
      'collection-34-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-23'),
      'collection-33-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-9'),
      'collection-32-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-18'),
      'collection-31-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-9-part-1'),
      'collection-30-episode-9-part-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 9 · Part 1',
      9,
      NULL,
      1,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-9'),
      'collection-28-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-5'),
      'collection-27-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-4'),
      'collection-26-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-14'),
      'collection-25-episode-14',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 14',
      14,
      NULL,
      NULL,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-16'),
      'collection-24-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-9'),
      'collection-23-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-9'),
      'collection-22-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-9'),
      'collection-21-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-9'),
      'collection-20-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-97'),
      'collection-18-episode-97',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 97',
      97,
      NULL,
      NULL,
      97,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-43'),
      'collection-17-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-26'),
      'collection-16-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-9'),
      'collection-11-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-9'),
      'collection-10-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-9'),
      'collection-8-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-9'),
      'collection-7-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-158'),
      'collection-77-episode-158',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 158',
      158,
      NULL,
      NULL,
      158,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-10'),
      'collection-73-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-121'),
      'collection-69-episode-121',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 121',
      121,
      NULL,
      NULL,
      121,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-10'),
      'collection-65-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-102'),
      'collection-63-episode-102',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 102',
      102,
      NULL,
      NULL,
      102,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-10'),
      'collection-61-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-77'),
      'collection-59-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-133'),
      'collection-50-bolum-133',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Bolum 133',
      NULL,
      133,
      NULL,
      133,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-89'),
      'collection-57-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-10'),
      'collection-6-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-54'),
      'collection-5-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-10'),
      'collection-4-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-29'),
      'collection-3-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-18'),
      'collection-2-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-10'),
      'collection-56-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-43'),
      'collection-53-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-31'),
      'collection-52-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-10'),
      'collection-51-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-10'),
      'collection-48-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-10'),
      'collection-47-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-10'),
      'collection-46-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-10'),
      'collection-43-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-10'),
      'collection-42-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-58'),
      'collection-40-episode-58',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 58',
      58,
      NULL,
      NULL,
      58,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-60'),
      'collection-36-episode-60',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 60',
      60,
      NULL,
      NULL,
      60,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-10'),
      'collection-34-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-24'),
      'collection-33-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-10'),
      'collection-32-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-19'),
      'collection-31-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-9-part-2'),
      'collection-30-episode-9-part-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      'Episode 9 · Part 2',
      9,
      NULL,
      2,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-10'),
      'collection-28-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-5'),
      'collection-26-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-10'),
      'collection-23-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-10'),
      'collection-22-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-10'),
      'collection-21-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-10'),
      'collection-20-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-98'),
      'collection-18-episode-98',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 98',
      98,
      NULL,
      NULL,
      98,
      'episode',
      'draft'
    )
ON CONFLICT (source_id) DO UPDATE SET
  label = CASE WHEN episode_groups.updated_at > episode_groups.created_at THEN episode_groups.label ELSE EXCLUDED.label END,
  reported_episode_number = EXCLUDED.reported_episode_number,
  bolum = EXCLUDED.bolum,
  part = EXCLUDED.part,
  order_key = EXCLUDED.order_key,
  status = CASE WHEN episode_groups.source_id LIKE 'collection-68%' THEN 'published' ELSE episode_groups.status END,
  updated_at = now();