INSERT INTO public.episode_groups (id, source_id, collection_id, label, reported_episode_number, bolum, part, order_key, content_type, status)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-65'),
      'collection-6-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-18'),
      'collection-5-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-65'),
      'collection-4-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-8'),
      'collection-3-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-68'),
      'collection-2-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-70'),
      'collection-56-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-65'),
      'collection-43-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-65'),
      'collection-34-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-60'),
      'collection-26-episode-60',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 60',
      60,
      NULL,
      NULL,
      60,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-8'),
      'collection-25-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-65'),
      'collection-23-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-66'),
      'collection-73-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-66'),
      'collection-61-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-161'),
      'collection-50-episode-161',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 161',
      161,
      NULL,
      NULL,
      161,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-66'),
      'collection-6-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-19'),
      'collection-5-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-66'),
      'collection-4-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-9'),
      'collection-3-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-69'),
      'collection-2-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-71'),
      'collection-56-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-66'),
      'collection-43-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-66'),
      'collection-34-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-61'),
      'collection-26-episode-61',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 61',
      61,
      NULL,
      NULL,
      61,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-66'),
      'collection-23-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-67'),
      'collection-73-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-67'),
      'collection-61-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-67'),
      'collection-6-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-20'),
      'collection-5-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-67'),
      'collection-4-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-10'),
      'collection-3-episode-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 10',
      10,
      NULL,
      NULL,
      10,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-7'),
      'collection-2-episode-7',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 7',
      7,
      NULL,
      NULL,
      7,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-72'),
      'collection-56-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-67'),
      'collection-43-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-67'),
      'collection-34-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-62'),
      'collection-26-episode-62',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 62',
      62,
      NULL,
      NULL,
      62,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-9'),
      'collection-25-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-67'),
      'collection-23-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-68'),
      'collection-73-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-68'),
      'collection-61-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-162'),
      'collection-50-episode-162',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 162',
      162,
      NULL,
      NULL,
      162,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-68'),
      'collection-6-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-21'),
      'collection-5-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-68'),
      'collection-4-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-11'),
      'collection-3-episode-11',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 11',
      11,
      NULL,
      NULL,
      11,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-70'),
      'collection-2-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-73'),
      'collection-56-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-68'),
      'collection-43-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-68'),
      'collection-34-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-63'),
      'collection-26-episode-63',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 63',
      63,
      NULL,
      NULL,
      63,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-68'),
      'collection-23-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-69'),
      'collection-73-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-69'),
      'collection-61-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-69'),
      'collection-6-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-22'),
      'collection-5-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-69'),
      'collection-4-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-12'),
      'collection-3-episode-12',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 12',
      12,
      NULL,
      NULL,
      12,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-71'),
      'collection-2-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-74'),
      'collection-56-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-69'),
      'collection-43-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-69'),
      'collection-34-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-64'),
      'collection-26-episode-64',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 64',
      64,
      NULL,
      NULL,
      64,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-70'),
      'collection-73-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-70'),
      'collection-61-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-163'),
      'collection-50-episode-163',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 163',
      163,
      NULL,
      NULL,
      163,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-70'),
      'collection-6-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-23'),
      'collection-5-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-70'),
      'collection-4-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-13'),
      'collection-3-episode-13',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 13',
      13,
      NULL,
      NULL,
      13,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-72'),
      'collection-2-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-75'),
      'collection-56-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-70'),
      'collection-43-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-70'),
      'collection-34-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-65'),
      'collection-26-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-71'),
      'collection-73-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-71'),
      'collection-61-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-71'),
      'collection-6-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-24'),
      'collection-5-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-71'),
      'collection-4-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-14'),
      'collection-3-episode-14',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 14',
      14,
      NULL,
      NULL,
      14,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-73'),
      'collection-2-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-76'),
      'collection-56-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-71'),
      'collection-43-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-71'),
      'collection-34-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-66'),
      'collection-26-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-72'),
      'collection-73-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-72'),
      'collection-61-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-164'),
      'collection-50-episode-164',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 164',
      164,
      NULL,
      NULL,
      164,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-72'),
      'collection-6-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-25'),
      'collection-5-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-72'),
      'collection-4-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-15'),
      'collection-3-episode-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 15',
      15,
      NULL,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-74'),
      'collection-2-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-77'),
      'collection-56-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-72'),
      'collection-43-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-72'),
      'collection-34-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-67'),
      'collection-26-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-73'),
      'collection-73-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-73'),
      'collection-61-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-73'),
      'collection-6-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-26'),
      'collection-5-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-73'),
      'collection-4-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-16'),
      'collection-3-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-75'),
      'collection-2-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-78'),
      'collection-56-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-73'),
      'collection-43-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-73'),
      'collection-34-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-68'),
      'collection-26-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-74'),
      'collection-73-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-74'),
      'collection-61-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-74'),
      'collection-6-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-27'),
      'collection-5-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-74'),
      'collection-4-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-17'),
      'collection-3-episode-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 17',
      17,
      NULL,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-76'),
      'collection-2-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-79'),
      'collection-56-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-74'),
      'collection-43-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-74'),
      'collection-34-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-69'),
      'collection-26-episode-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 69',
      69,
      NULL,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-75'),
      'collection-73-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-75'),
      'collection-61-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-75'),
      'collection-6-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-28'),
      'collection-5-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-75'),
      'collection-4-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-18'),
      'collection-3-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-8'),
      'collection-2-episode-8',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 8',
      8,
      NULL,
      NULL,
      8,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-80'),
      'collection-56-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-75'),
      'collection-43-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-75'),
      'collection-34-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-70'),
      'collection-26-episode-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 70',
      70,
      NULL,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-76'),
      'collection-73-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-76'),
      'collection-61-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-76'),
      'collection-6-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-29'),
      'collection-5-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-76'),
      'collection-4-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-19'),
      'collection-3-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-9'),
      'collection-2-episode-9',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 9',
      9,
      NULL,
      NULL,
      9,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-81'),
      'collection-56-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-76'),
      'collection-43-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-76'),
      'collection-34-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-71'),
      'collection-26-episode-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 71',
      71,
      NULL,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-77'),
      'collection-73-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-77'),
      'collection-61-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-77'),
      'collection-6-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-30'),
      'collection-5-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-77'),
      'collection-4-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-82'),
      'collection-56-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-77'),
      'collection-43-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-77'),
      'collection-34-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-72'),
      'collection-26-episode-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 72',
      72,
      NULL,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-78'),
      'collection-73-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-78'),
      'collection-61-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-78'),
      'collection-6-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-31'),
      'collection-5-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-78'),
      'collection-4-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-83'),
      'collection-56-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-78'),
      'collection-43-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-78'),
      'collection-34-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-73'),
      'collection-26-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-79'),
      'collection-73-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-79'),
      'collection-61-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-79'),
      'collection-6-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-32'),
      'collection-5-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-79'),
      'collection-4-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-84'),
      'collection-56-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-79'),
      'collection-43-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-79'),
      'collection-34-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-74'),
      'collection-26-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-80'),
      'collection-73-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-80'),
      'collection-61-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-80'),
      'collection-6-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-33'),
      'collection-5-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-80'),
      'collection-4-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-85'),
      'collection-56-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-80'),
      'collection-43-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-80'),
      'collection-34-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-75'),
      'collection-26-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-81'),
      'collection-73-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-81'),
      'collection-61-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-81'),
      'collection-6-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-34'),
      'collection-5-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-81'),
      'collection-4-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-86'),
      'collection-56-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-81'),
      'collection-43-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-81'),
      'collection-34-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-76'),
      'collection-26-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-82'),
      'collection-73-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-82'),
      'collection-61-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-82'),
      'collection-6-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-35'),
      'collection-5-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-82'),
      'collection-4-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-87'),
      'collection-56-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-82'),
      'collection-43-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-82'),
      'collection-34-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-77'),
      'collection-26-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-83'),
      'collection-73-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-83'),
      'collection-61-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-83'),
      'collection-6-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-36'),
      'collection-5-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-83'),
      'collection-4-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-88'),
      'collection-56-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-83'),
      'collection-43-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-83'),
      'collection-34-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-78'),
      'collection-26-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-84'),
      'collection-73-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-84'),
      'collection-61-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-84'),
      'collection-6-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-37'),
      'collection-5-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-84'),
      'collection-4-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-89'),
      'collection-56-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-84'),
      'collection-43-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-84'),
      'collection-34-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-79'),
      'collection-26-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-85'),
      'collection-73-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-85'),
      'collection-61-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-85'),
      'collection-6-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-38'),
      'collection-5-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-85'),
      'collection-4-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-90'),
      'collection-56-episode-90',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 90',
      90,
      NULL,
      NULL,
      90,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-85'),
      'collection-43-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-85'),
      'collection-34-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-80'),
      'collection-26-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-86'),
      'collection-73-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-86'),
      'collection-61-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-86'),
      'collection-6-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-39'),
      'collection-5-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-86'),
      'collection-4-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-91'),
      'collection-56-episode-91',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 91',
      91,
      NULL,
      NULL,
      91,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-86'),
      'collection-43-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-86'),
      'collection-34-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-81'),
      'collection-26-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-87'),
      'collection-73-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-87'),
      'collection-61-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-87'),
      'collection-6-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-40'),
      'collection-5-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-87'),
      'collection-4-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-92'),
      'collection-56-episode-92',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 92',
      92,
      NULL,
      NULL,
      92,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-87'),
      'collection-43-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-87'),
      'collection-34-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-82'),
      'collection-26-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-88'),
      'collection-73-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-88'),
      'collection-61-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-88'),
      'collection-6-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-41'),
      'collection-5-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-88'),
      'collection-4-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-93'),
      'collection-56-episode-93',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 93',
      93,
      NULL,
      NULL,
      93,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-88'),
      'collection-43-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-88'),
      'collection-34-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-83'),
      'collection-26-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-89'),
      'collection-73-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-89'),
      'collection-61-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    )
ON CONFLICT (source_id) DO UPDATE SET
  label = CASE WHEN episode_groups.updated_at > episode_groups.created_at THEN episode_groups.label ELSE EXCLUDED.label END,
  reported_episode_number = EXCLUDED.reported_episode_number,
  bolum = EXCLUDED.bolum,
  part = EXCLUDED.part,
  order_key = EXCLUDED.order_key,
  status = CASE WHEN episode_groups.source_id LIKE 'collection-68%' THEN 'published' ELSE episode_groups.status END,
  updated_at = now();