INSERT INTO public.episode_groups (id, source_id, collection_id, label, reported_episode_number, bolum, part, order_key, content_type, status)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-148'),
      'collection-69-episode-148',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 148',
      148,
      NULL,
      NULL,
      148,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-129'),
      'collection-63-episode-129',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 129',
      129,
      NULL,
      NULL,
      129,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-37'),
      'collection-61-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-37'),
      'collection-6-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-81'),
      'collection-5-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-37'),
      'collection-4-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-56'),
      'collection-3-episode-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 56',
      56,
      NULL,
      NULL,
      56,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-42'),
      'collection-2-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-42'),
      'collection-56-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-37'),
      'collection-43-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-episode-19'),
      'collection-41-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-117'),
      'collection-38-bolum-117',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 117',
      NULL,
      117,
      NULL,
      117,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-50'),
      'collection-37-bolum-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 23 · Bolum 50',
      23,
      50,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-37'),
      'collection-34-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-46'),
      'collection-31-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-19'),
      'collection-27-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-32'),
      'collection-26-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-28'),
      'collection-25-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-30'),
      'collection-24-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-37'),
      'collection-23-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-51'),
      'collection-16-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-37'),
      'collection-10-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-33'),
      'collection-8-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-70'),
      'collection-76-bolum-70',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 70 · Bolum 70',
      70,
      70,
      NULL,
      70,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-38'),
      'collection-73-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-130'),
      'collection-63-episode-130',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 130',
      130,
      NULL,
      NULL,
      130,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-38'),
      'collection-61-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-147'),
      'collection-50-episode-147',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 147',
      147,
      NULL,
      NULL,
      147,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-38'),
      'collection-6-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-82'),
      'collection-5-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-38'),
      'collection-4-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-57'),
      'collection-3-episode-57',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 57',
      57,
      NULL,
      NULL,
      57,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-43'),
      'collection-2-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-43'),
      'collection-56-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-38'),
      'collection-43-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-38'),
      'collection-34-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-47'),
      'collection-31-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-33'),
      'collection-26-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-38'),
      'collection-23-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-52'),
      'collection-16-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-38'),
      'collection-10-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-20'),
      'collection-78-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-39'),
      'collection-73-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-48'),
      'collection-71-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-184'),
      'collection-70-episode-184',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 184',
      184,
      NULL,
      NULL,
      184,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-131'),
      'collection-63-episode-131',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 131',
      131,
      NULL,
      NULL,
      131,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-39'),
      'collection-61-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-39'),
      'collection-6-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-83'),
      'collection-5-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-39'),
      'collection-4-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-58'),
      'collection-3-episode-58',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 58',
      58,
      NULL,
      NULL,
      58,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-44'),
      'collection-2-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-44'),
      'collection-56-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-39'),
      'collection-43-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-episode-20'),
      'collection-41-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-118'),
      'collection-38-bolum-118',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 118',
      NULL,
      118,
      NULL,
      118,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-51'),
      'collection-37-bolum-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 24 · Bolum 51',
      24,
      51,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-39'),
      'collection-34-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-48'),
      'collection-31-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-20'),
      'collection-27-episode-20',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 20',
      20,
      NULL,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-34'),
      'collection-26-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-29'),
      'collection-25-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-31'),
      'collection-24-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-39'),
      'collection-23-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-53'),
      'collection-16-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-39'),
      'collection-10-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-34'),
      'collection-8-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-71'),
      'collection-76-bolum-71',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 71 · Bolum 71',
      71,
      71,
      NULL,
      71,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-40'),
      'collection-73-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-40'),
      'collection-61-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-148'),
      'collection-50-episode-148',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 148',
      148,
      NULL,
      NULL,
      148,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-40'),
      'collection-6-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-84'),
      'collection-5-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-40'),
      'collection-4-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-59'),
      'collection-3-episode-59',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 59',
      59,
      NULL,
      NULL,
      59,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-45'),
      'collection-2-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-45'),
      'collection-56-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-40'),
      'collection-43-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-40'),
      'collection-34-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-49'),
      'collection-31-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-35'),
      'collection-26-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-40'),
      'collection-23-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-54'),
      'collection-16-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-40'),
      'collection-10-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-35'),
      'collection-8-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-21'),
      'collection-78-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-41'),
      'collection-73-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-49'),
      'collection-71-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-185'),
      'collection-70-episode-185',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 185',
      185,
      NULL,
      NULL,
      185,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-41'),
      'collection-61-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-41'),
      'collection-6-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-85'),
      'collection-5-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-41'),
      'collection-4-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-60'),
      'collection-3-episode-60',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 60',
      60,
      NULL,
      NULL,
      60,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-46'),
      'collection-2-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-46'),
      'collection-56-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-41'),
      'collection-43-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-119'),
      'collection-38-bolum-119',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 119',
      NULL,
      119,
      NULL,
      119,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-52'),
      'collection-37-bolum-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 25 · Bolum 52',
      25,
      52,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-41'),
      'collection-34-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-50'),
      'collection-31-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-21'),
      'collection-27-episode-21',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 21',
      21,
      NULL,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-36'),
      'collection-26-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-30'),
      'collection-25-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-32'),
      'collection-24-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-41'),
      'collection-23-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-41'),
      'collection-10-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-72'),
      'collection-76-bolum-72',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 72 · Bolum 72',
      72,
      72,
      NULL,
      72,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-42'),
      'collection-73-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-42'),
      'collection-61-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-149'),
      'collection-50-episode-149',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 149',
      149,
      NULL,
      NULL,
      149,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-42'),
      'collection-6-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-86'),
      'collection-5-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-42'),
      'collection-4-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-61'),
      'collection-3-episode-61',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 61',
      61,
      NULL,
      NULL,
      61,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-47'),
      'collection-2-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-47'),
      'collection-56-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-42'),
      'collection-43-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-42'),
      'collection-34-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-37'),
      'collection-26-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-42'),
      'collection-23-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-42'),
      'collection-10-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-36'),
      'collection-8-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-22'),
      'collection-78-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-43'),
      'collection-73-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-50'),
      'collection-71-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-186'),
      'collection-70-episode-186',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 186',
      186,
      NULL,
      NULL,
      186,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-43'),
      'collection-61-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-43'),
      'collection-6-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-87'),
      'collection-5-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-43'),
      'collection-4-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-62'),
      'collection-3-episode-62',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 62',
      62,
      NULL,
      NULL,
      62,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-48'),
      'collection-2-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-48'),
      'collection-56-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-43'),
      'collection-43-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-120'),
      'collection-38-bolum-120',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 120',
      NULL,
      120,
      NULL,
      120,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-53'),
      'collection-37-bolum-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 26 · Bolum 53',
      26,
      53,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-43'),
      'collection-34-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-22'),
      'collection-27-episode-22',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 22',
      22,
      NULL,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-38'),
      'collection-26-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-31'),
      'collection-25-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-1'),
      'collection-24-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-43'),
      'collection-23-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-43'),
      'collection-10-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-73'),
      'collection-76-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-44'),
      'collection-73-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-44'),
      'collection-61-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-150'),
      'collection-50-episode-150',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 150',
      150,
      NULL,
      NULL,
      150,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-44'),
      'collection-6-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-88'),
      'collection-5-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-44'),
      'collection-4-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-49'),
      'collection-2-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-49'),
      'collection-56-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-44'),
      'collection-43-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-44'),
      'collection-34-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-39'),
      'collection-26-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-44'),
      'collection-23-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-44'),
      'collection-10-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-37'),
      'collection-8-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-23'),
      'collection-78-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-45'),
      'collection-73-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-51'),
      'collection-71-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-187'),
      'collection-70-episode-187',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 187',
      187,
      NULL,
      NULL,
      187,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-45'),
      'collection-61-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-45'),
      'collection-6-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-89'),
      'collection-5-episode-89',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 89',
      89,
      NULL,
      NULL,
      89,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-45'),
      'collection-4-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-64'),
      'collection-3-episode-64',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 64',
      64,
      NULL,
      NULL,
      64,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-5'),
      'collection-2-episode-5',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 5',
      5,
      NULL,
      NULL,
      5,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-50'),
      'collection-56-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-45'),
      'collection-43-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-121'),
      'collection-38-bolum-121',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 121',
      NULL,
      121,
      NULL,
      121,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-54'),
      'collection-37-bolum-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 27 · Bolum 54',
      27,
      54,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-45'),
      'collection-34-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-23'),
      'collection-27-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-40'),
      'collection-26-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-32'),
      'collection-25-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-2'),
      'collection-24-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-45'),
      'collection-23-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-45'),
      'collection-10-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-74'),
      'collection-76-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-46'),
      'collection-73-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-46'),
      'collection-61-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-151'),
      'collection-50-episode-151',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 151',
      151,
      NULL,
      NULL,
      151,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-46'),
      'collection-6-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-90'),
      'collection-5-episode-90',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 90',
      90,
      NULL,
      NULL,
      90,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-46'),
      'collection-4-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-65'),
      'collection-3-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-50'),
      'collection-2-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-51'),
      'collection-56-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-46'),
      'collection-43-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-46'),
      'collection-34-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-41'),
      'collection-26-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-46'),
      'collection-23-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-46'),
      'collection-10-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-24'),
      'collection-78-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-47'),
      'collection-73-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-52'),
      'collection-71-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-188'),
      'collection-70-episode-188',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 188',
      188,
      NULL,
      NULL,
      188,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-47'),
      'collection-61-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-47'),
      'collection-6-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-91'),
      'collection-5-episode-91',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 91',
      91,
      NULL,
      NULL,
      91,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-47'),
      'collection-4-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-66'),
      'collection-3-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-51'),
      'collection-2-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-52'),
      'collection-56-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-47'),
      'collection-43-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-122'),
      'collection-38-bolum-122',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 122',
      NULL,
      122,
      NULL,
      122,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-55'),
      'collection-37-bolum-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 28 · Bolum 55',
      28,
      55,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-47'),
      'collection-34-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-24'),
      'collection-27-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-42'),
      'collection-26-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-33'),
      'collection-25-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-3'),
      'collection-24-episode-3',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 3',
      3,
      NULL,
      NULL,
      3,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-47'),
      'collection-23-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-47'),
      'collection-10-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-75'),
      'collection-76-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-48'),
      'collection-73-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-48'),
      'collection-61-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-152'),
      'collection-50-episode-152',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 152',
      152,
      NULL,
      NULL,
      152,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-48'),
      'collection-6-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-1'),
      'collection-5-episode-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 1',
      1,
      NULL,
      NULL,
      1,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-48'),
      'collection-4-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-67'),
      'collection-3-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-52'),
      'collection-2-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-53'),
      'collection-56-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-48'),
      'collection-43-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-48'),
      'collection-34-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-43'),
      'collection-26-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-48'),
      'collection-23-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-48'),
      'collection-10-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-25'),
      'collection-78-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-49'),
      'collection-73-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-53'),
      'collection-71-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-189'),
      'collection-70-episode-189',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 189',
      189,
      NULL,
      NULL,
      189,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-49'),
      'collection-61-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-49'),
      'collection-6-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-2'),
      'collection-5-episode-2',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 2',
      2,
      NULL,
      NULL,
      2,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-49'),
      'collection-4-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-68'),
      'collection-3-episode-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 68',
      68,
      NULL,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-53'),
      'collection-2-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-54'),
      'collection-56-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-49'),
      'collection-43-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-123'),
      'collection-38-bolum-123',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 123',
      NULL,
      123,
      NULL,
      123,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-56'),
      'collection-37-bolum-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 29 · Bolum 56',
      29,
      56,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-49'),
      'collection-34-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-25'),
      'collection-27-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-44'),
      'collection-26-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-34'),
      'collection-25-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-4'),
      'collection-24-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    )
ON CONFLICT (source_id) DO UPDATE SET
  label = CASE WHEN episode_groups.updated_at > episode_groups.created_at THEN episode_groups.label ELSE EXCLUDED.label END,
  reported_episode_number = EXCLUDED.reported_episode_number,
  bolum = EXCLUDED.bolum,
  part = EXCLUDED.part,
  order_key = EXCLUDED.order_key,
  status = CASE WHEN episode_groups.source_id LIKE 'collection-68%' THEN 'published' ELSE episode_groups.status END,
  updated_at = now();