INSERT INTO public.episode_groups (id, source_id, collection_id, label, reported_episode_number, bolum, part, order_key, content_type, status)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-23'),
      'collection-26-episode-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 23',
      23,
      NULL,
      NULL,
      23,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-28'),
      'collection-23-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-116'),
      'collection-18-episode-116',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 116',
      116,
      NULL,
      NULL,
      116,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-82'),
      'collection-17-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-42'),
      'collection-16-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-28'),
      'collection-10-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-28'),
      'collection-8-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-15'),
      'collection-78-bolum-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 15 · Bolum 15',
      15,
      15,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-177'),
      'collection-77-episode-177',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 177',
      177,
      NULL,
      NULL,
      177,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-29'),
      'collection-73-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-43'),
      'collection-71-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-179'),
      'collection-70-episode-179',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 179',
      179,
      NULL,
      NULL,
      179,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-140'),
      'collection-69-episode-140',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 140',
      140,
      NULL,
      NULL,
      140,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-29'),
      'collection-65-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-121'),
      'collection-63-episode-121',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 121',
      121,
      NULL,
      NULL,
      121,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-29'),
      'collection-61-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-142'),
      'collection-50-bolum-142',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Bolum 142',
      NULL,
      142,
      NULL,
      142,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-108'),
      'collection-57-episode-108',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 108',
      108,
      NULL,
      NULL,
      108,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-29'),
      'collection-6-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-73'),
      'collection-5-episode-73',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 73',
      73,
      NULL,
      NULL,
      73,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-29'),
      'collection-4-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-48'),
      'collection-3-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-35'),
      'collection-2-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-34'),
      'collection-56-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-62'),
      'collection-53-episode-62',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 62',
      62,
      NULL,
      NULL,
      62,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-50'),
      'collection-52-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-29'),
      'collection-48-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-29'),
      'collection-43-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-47'),
      'collection-41-bolum-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 15 · Bolum 47',
      15,
      47,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-77'),
      'collection-40-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-113'),
      'collection-38-bolum-113',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Episode 15 · Bolum 113',
      15,
      113,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-46'),
      'collection-37-bolum-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 19 · Bolum 46',
      19,
      46,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-79'),
      'collection-36-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-29'),
      'collection-34-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-43'),
      'collection-33-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-38'),
      'collection-31-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-15'),
      'collection-27-episode-15',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 15',
      15,
      NULL,
      NULL,
      15,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-24'),
      'collection-26-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-24'),
      'collection-25-episode-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 24',
      24,
      NULL,
      NULL,
      24,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-26'),
      'collection-24-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-29'),
      'collection-23-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-117'),
      'collection-18-episode-117',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 117',
      117,
      NULL,
      NULL,
      117,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-83'),
      'collection-17-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-43'),
      'collection-16-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-29'),
      'collection-10-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-29'),
      'collection-8-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-178'),
      'collection-77-episode-178',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 178',
      178,
      NULL,
      NULL,
      178,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-66'),
      'collection-76-bolum-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 66 · Bolum 66',
      66,
      66,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-30'),
      'collection-73-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-141'),
      'collection-69-episode-141',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 141',
      141,
      NULL,
      NULL,
      141,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-122'),
      'collection-63-episode-122',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 122',
      122,
      NULL,
      NULL,
      122,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-30'),
      'collection-61-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-143'),
      'collection-50-episode-143',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 143',
      143,
      NULL,
      NULL,
      143,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-109'),
      'collection-57-episode-109',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 109',
      109,
      NULL,
      NULL,
      109,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-30'),
      'collection-6-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-74'),
      'collection-5-episode-74',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 74',
      74,
      NULL,
      NULL,
      74,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-30'),
      'collection-4-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-49'),
      'collection-3-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-36'),
      'collection-2-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-35'),
      'collection-56-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-63'),
      'collection-53-episode-63',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 63',
      63,
      NULL,
      NULL,
      63,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-51'),
      'collection-52-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-30'),
      'collection-48-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-30'),
      'collection-43-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-78'),
      'collection-40-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-80'),
      'collection-36-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-30'),
      'collection-34-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-44'),
      'collection-33-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-39'),
      'collection-31-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-25'),
      'collection-26-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-30'),
      'collection-23-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-118'),
      'collection-18-episode-118',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 118',
      118,
      NULL,
      NULL,
      118,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-84'),
      'collection-17-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-44'),
      'collection-16-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-30'),
      'collection-10-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-16'),
      'collection-78-bolum-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 16 · Bolum 16',
      16,
      16,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-179'),
      'collection-77-episode-179',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 179',
      179,
      NULL,
      NULL,
      179,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-31'),
      'collection-73-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-44'),
      'collection-71-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-180'),
      'collection-70-episode-180',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 180',
      180,
      NULL,
      NULL,
      180,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-142'),
      'collection-69-episode-142',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 142',
      142,
      NULL,
      NULL,
      142,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-123'),
      'collection-63-episode-123',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 123',
      123,
      NULL,
      NULL,
      123,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-31'),
      'collection-61-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-143'),
      'collection-50-bolum-143',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Bolum 143',
      NULL,
      143,
      NULL,
      143,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-110'),
      'collection-57-episode-110',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 110',
      110,
      NULL,
      NULL,
      110,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-31'),
      'collection-6-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-75'),
      'collection-5-episode-75',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 75',
      75,
      NULL,
      NULL,
      75,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-31'),
      'collection-4-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-50'),
      'collection-3-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-37'),
      'collection-2-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-36'),
      'collection-56-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-64'),
      'collection-53-episode-64',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 64',
      64,
      NULL,
      NULL,
      64,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-52'),
      'collection-52-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-31'),
      'collection-48-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-31'),
      'collection-43-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-48'),
      'collection-41-bolum-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 16 · Bolum 48',
      16,
      48,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-79'),
      'collection-40-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-114'),
      'collection-38-bolum-114',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 114',
      NULL,
      114,
      NULL,
      114,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-47'),
      'collection-37-bolum-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 20 · Bolum 47',
      20,
      47,
      NULL,
      20,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-81'),
      'collection-36-episode-81',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 81',
      81,
      NULL,
      NULL,
      81,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-31'),
      'collection-34-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-45'),
      'collection-33-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-40'),
      'collection-31-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-16'),
      'collection-27-episode-16',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 16',
      16,
      NULL,
      NULL,
      16,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-26'),
      'collection-26-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-25'),
      'collection-25-episode-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 25',
      25,
      NULL,
      NULL,
      25,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-27'),
      'collection-24-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-31'),
      'collection-23-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-119'),
      'collection-18-episode-119',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      'Episode 119',
      119,
      NULL,
      NULL,
      119,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-85'),
      'collection-17-episode-85',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 85',
      85,
      NULL,
      NULL,
      85,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-45'),
      'collection-16-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-31'),
      'collection-10-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-30'),
      'collection-8-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-180'),
      'collection-77-episode-180',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 180',
      180,
      NULL,
      NULL,
      180,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-67'),
      'collection-76-bolum-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 67 · Bolum 67',
      67,
      67,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-32'),
      'collection-73-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-143'),
      'collection-69-episode-143',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 143',
      143,
      NULL,
      NULL,
      143,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-124'),
      'collection-63-episode-124',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 124',
      124,
      NULL,
      NULL,
      124,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-32'),
      'collection-61-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-144'),
      'collection-50-episode-144',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 144',
      144,
      NULL,
      NULL,
      144,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-111'),
      'collection-57-episode-111',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      'Episode 111',
      111,
      NULL,
      NULL,
      111,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-32'),
      'collection-6-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-76'),
      'collection-5-episode-76',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 76',
      76,
      NULL,
      NULL,
      76,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-32'),
      'collection-4-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-51'),
      'collection-3-episode-51',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 51',
      51,
      NULL,
      NULL,
      51,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-38'),
      'collection-2-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-37'),
      'collection-56-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-65'),
      'collection-53-episode-65',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 65',
      65,
      NULL,
      NULL,
      65,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-53'),
      'collection-52-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-32'),
      'collection-48-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-32'),
      'collection-43-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-82'),
      'collection-36-episode-82',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 82',
      82,
      NULL,
      NULL,
      82,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-32'),
      'collection-34-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-46'),
      'collection-33-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-41'),
      'collection-31-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-27'),
      'collection-26-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-32'),
      'collection-23-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-86'),
      'collection-17-episode-86',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 86',
      86,
      NULL,
      NULL,
      86,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-46'),
      'collection-16-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-32'),
      'collection-10-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-17'),
      'collection-78-bolum-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 17 · Bolum 17',
      17,
      17,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-181'),
      'collection-77-episode-181',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 181',
      181,
      NULL,
      NULL,
      181,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-33'),
      'collection-73-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-45'),
      'collection-71-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-181'),
      'collection-70-episode-181',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 181',
      181,
      NULL,
      NULL,
      181,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-144'),
      'collection-69-episode-144',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 144',
      144,
      NULL,
      NULL,
      144,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-125'),
      'collection-63-episode-125',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 125',
      125,
      NULL,
      NULL,
      125,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-33'),
      'collection-61-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-33'),
      'collection-6-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-77'),
      'collection-5-episode-77',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 77',
      77,
      NULL,
      NULL,
      77,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-33'),
      'collection-4-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-52'),
      'collection-3-episode-52',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 52',
      52,
      NULL,
      NULL,
      52,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-39'),
      'collection-2-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-38'),
      'collection-56-episode-38',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 38',
      38,
      NULL,
      NULL,
      38,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-66'),
      'collection-53-episode-66',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 66',
      66,
      NULL,
      NULL,
      66,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-54'),
      'collection-52-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-33'),
      'collection-48-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-33'),
      'collection-43-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-49'),
      'collection-41-bolum-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 17 · Bolum 49',
      17,
      49,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-115'),
      'collection-38-bolum-115',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 115',
      NULL,
      115,
      NULL,
      115,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-48'),
      'collection-37-bolum-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 21 · Bolum 48',
      21,
      48,
      NULL,
      21,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-83'),
      'collection-36-episode-83',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 83',
      83,
      NULL,
      NULL,
      83,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-33'),
      'collection-34-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-47'),
      'collection-33-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-42'),
      'collection-31-episode-42',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 42',
      42,
      NULL,
      NULL,
      42,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-17'),
      'collection-27-episode-17',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 17',
      17,
      NULL,
      NULL,
      17,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-28'),
      'collection-26-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-26'),
      'collection-25-episode-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 26',
      26,
      NULL,
      NULL,
      26,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-28'),
      'collection-24-episode-28',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 28',
      28,
      NULL,
      NULL,
      28,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-33'),
      'collection-23-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-87'),
      'collection-17-episode-87',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 87',
      87,
      NULL,
      NULL,
      87,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-47'),
      'collection-16-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-33'),
      'collection-10-episode-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 33',
      33,
      NULL,
      NULL,
      33,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-31'),
      'collection-8-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-182'),
      'collection-77-episode-182',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 182',
      182,
      NULL,
      NULL,
      182,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-68'),
      'collection-76-bolum-68',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 68 · Bolum 68',
      68,
      68,
      NULL,
      68,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-34'),
      'collection-73-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-145'),
      'collection-69-episode-145',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 145',
      145,
      NULL,
      NULL,
      145,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-126'),
      'collection-63-episode-126',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 126',
      126,
      NULL,
      NULL,
      126,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-34'),
      'collection-61-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-145'),
      'collection-50-episode-145',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 145',
      145,
      NULL,
      NULL,
      145,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-34'),
      'collection-6-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-78'),
      'collection-5-episode-78',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 78',
      78,
      NULL,
      NULL,
      78,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-34'),
      'collection-4-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-53'),
      'collection-3-episode-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 53',
      53,
      NULL,
      NULL,
      53,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-4'),
      'collection-2-episode-4',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 4',
      4,
      NULL,
      NULL,
      4,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-39'),
      'collection-56-episode-39',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 39',
      39,
      NULL,
      NULL,
      39,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-67'),
      'collection-53-episode-67',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      'Episode 67',
      67,
      NULL,
      NULL,
      67,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-34'),
      'collection-43-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-84'),
      'collection-36-episode-84',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      'Episode 84',
      84,
      NULL,
      NULL,
      84,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-34'),
      'collection-34-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-48'),
      'collection-33-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-43'),
      'collection-31-episode-43',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 43',
      43,
      NULL,
      NULL,
      43,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-29'),
      'collection-26-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-34'),
      'collection-23-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-88'),
      'collection-17-episode-88',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      'Episode 88',
      88,
      NULL,
      NULL,
      88,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-48'),
      'collection-16-episode-48',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 48',
      48,
      NULL,
      NULL,
      48,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-34'),
      'collection-10-episode-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 34',
      34,
      NULL,
      NULL,
      34,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-18'),
      'collection-78-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-183'),
      'collection-77-episode-183',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 183',
      183,
      NULL,
      NULL,
      183,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-35'),
      'collection-73-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-46'),
      'collection-71-episode-46',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 46',
      46,
      NULL,
      NULL,
      46,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-182'),
      'collection-70-episode-182',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 182',
      182,
      NULL,
      NULL,
      182,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-146'),
      'collection-69-episode-146',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 146',
      146,
      NULL,
      NULL,
      146,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-127'),
      'collection-63-episode-127',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 127',
      127,
      NULL,
      NULL,
      127,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-35'),
      'collection-61-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-35'),
      'collection-6-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-79'),
      'collection-5-episode-79',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 79',
      79,
      NULL,
      NULL,
      79,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-35'),
      'collection-4-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-54'),
      'collection-3-episode-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 54',
      54,
      NULL,
      NULL,
      54,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-40'),
      'collection-2-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-40'),
      'collection-56-episode-40',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 40',
      40,
      NULL,
      NULL,
      40,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-35'),
      'collection-43-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-50'),
      'collection-41-bolum-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      'Episode 18 · Bolum 50',
      18,
      50,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-116'),
      'collection-38-bolum-116',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      'Bolum 116',
      NULL,
      116,
      NULL,
      116,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-49'),
      'collection-37-bolum-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      'Episode 22 · Bolum 49',
      22,
      49,
      NULL,
      22,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-35'),
      'collection-34-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-44'),
      'collection-31-episode-44',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 44',
      44,
      NULL,
      NULL,
      44,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-18'),
      'collection-27-episode-18',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      'Episode 18',
      18,
      NULL,
      NULL,
      18,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-30'),
      'collection-26-episode-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 30',
      30,
      NULL,
      NULL,
      30,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-27'),
      'collection-25-episode-27',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      'Episode 27',
      27,
      NULL,
      NULL,
      27,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-29'),
      'collection-24-episode-29',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      'Episode 29',
      29,
      NULL,
      NULL,
      29,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-35'),
      'collection-23-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-49'),
      'collection-16-episode-49',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 49',
      49,
      NULL,
      NULL,
      49,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-35'),
      'collection-10-episode-35',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 35',
      35,
      NULL,
      NULL,
      35,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-32'),
      'collection-8-episode-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      'Episode 32',
      32,
      NULL,
      NULL,
      32,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-184'),
      'collection-77-episode-184',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      'Episode 184',
      184,
      NULL,
      NULL,
      184,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-69'),
      'collection-76-bolum-69',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      'Episode 69 · Bolum 69',
      69,
      69,
      NULL,
      69,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-36'),
      'collection-73-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-147'),
      'collection-69-episode-147',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      'Episode 147',
      147,
      NULL,
      NULL,
      147,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-128'),
      'collection-63-episode-128',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      'Episode 128',
      128,
      NULL,
      NULL,
      128,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-36'),
      'collection-61-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-146'),
      'collection-50-episode-146',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      'Episode 146',
      146,
      NULL,
      NULL,
      146,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-36'),
      'collection-6-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-80'),
      'collection-5-episode-80',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      'Episode 80',
      80,
      NULL,
      NULL,
      80,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-36'),
      'collection-4-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-55'),
      'collection-3-episode-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      'Episode 55',
      55,
      NULL,
      NULL,
      55,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-41'),
      'collection-2-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-41'),
      'collection-56-episode-41',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      'Episode 41',
      41,
      NULL,
      NULL,
      41,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-36'),
      'collection-43-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-36'),
      'collection-34-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-45'),
      'collection-31-episode-45',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      'Episode 45',
      45,
      NULL,
      NULL,
      45,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-31'),
      'collection-26-episode-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      'Episode 31',
      31,
      NULL,
      NULL,
      31,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-36'),
      'collection-23-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-50'),
      'collection-16-episode-50',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      'Episode 50',
      50,
      NULL,
      NULL,
      50,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-36'),
      'collection-10-episode-36',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      'Episode 36',
      36,
      NULL,
      NULL,
      36,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-19'),
      'collection-78-episode-19',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      'Episode 19',
      19,
      NULL,
      NULL,
      19,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-37'),
      'collection-73-episode-37',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      'Episode 37',
      37,
      NULL,
      NULL,
      37,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-47'),
      'collection-71-episode-47',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      'Episode 47',
      47,
      NULL,
      NULL,
      47,
      'episode',
      'draft'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-183'),
      'collection-70-episode-183',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      'Episode 183',
      183,
      NULL,
      NULL,
      183,
      'episode',
      'draft'
    )
ON CONFLICT (source_id) DO UPDATE SET
  label = CASE WHEN episode_groups.updated_at > episode_groups.created_at THEN episode_groups.label ELSE EXCLUDED.label END,
  reported_episode_number = EXCLUDED.reported_episode_number,
  bolum = EXCLUDED.bolum,
  part = EXCLUDED.part,
  order_key = EXCLUDED.order_key,
  status = CASE WHEN episode_groups.source_id LIKE 'collection-68%' THEN 'published' ELSE episode_groups.status END,
  updated_at = now();