INSERT INTO public.video_variants (id, source_id, collection_id, group_id, display_label, reported_season, languages, version, publication_state, duration_seconds, thumbnail_url)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4082'),
      'video-4082',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-84'),
      'Episode 1 · Bolum 84',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1789363783.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4103'),
      'video-4103',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-88'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-88-bolum-84'),
      'Episode 1 · Bolum 84',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790678305.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4101'),
      'video-4101',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-87'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-87-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790673829.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4100'),
      'video-4100',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-86'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-86-bolum-32'),
      'Episode 1 · Bolum 32',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790665405.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4091'),
      'video-4091',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-84'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-84-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1789825332.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4090'),
      'video-4090',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-83'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-83-bolum-185'),
      'Episode 1 · Bolum 185',
      7,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1789715080.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3896'),
      'video-3896',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1760630787.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3886'),
      'video-3886',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-149'),
      'Episode 149 · Bolum 149',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1758728559.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3884'),
      'video-3884',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-50'),
      'Episode 50',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1749626631.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3253'),
      'video-3253',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-1'),
      'Episode 1',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3245'),
      'video-3245',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729356394.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3240'),
      'video-3240',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-29'),
      'Episode 29',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729010385.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3219'),
      'video-3219',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-165'),
      'Episode 165',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726975814.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3208'),
      'video-3208',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-1'),
      'Episode 1',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1725773541.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3051'),
      'video-3051',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1719209521.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2902'),
      'video-2902',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-93'),
      'Episode 93',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1714276335.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2555'),
      'video-2555',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-1'),
      'Episode 1',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1700453222.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2536'),
      'video-2536',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-68'),
      'Episode 68',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698381395.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2400'),
      'video-2400',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      NULL,
      'Kurulus Osman Season 5: Shooting & Release Date',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1692258885.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2465'),
      'video-2465',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-80'),
      'Episode 80',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1695299134.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1047'),
      'video-1047',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-1'),
      'Episode 1',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1000'),
      'video-1000',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-45'),
      'Episode 45',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-210'),
      'video-210',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-1'),
      'Episode 1',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-100'),
      'video-100',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-20'),
      'Episode 20',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1'),
      'video-1',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3772'),
      'video-3772',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2450'),
      'video-2450',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-34'),
      'Episode 34',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2424'),
      'video-2424',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-22'),
      'Episode 22',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694089133.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2415'),
      'video-2415',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693571368.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2394'),
      'video-2394',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1691646650.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2366'),
      'video-2366',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2338'),
      'video-2338',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2099'),
      'video-2099',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-1'),
      'Episode 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1679938799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1892'),
      'video-1892',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-1'),
      'Episode 1',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1867'),
      'video-1867',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1861'),
      'video-1861',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-33'),
      'Episode 1 · Bolum 33',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1832'),
      'video-1832',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-49'),
      'Episode 49',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1812'),
      'video-1812',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-99'),
      'Episode 1 · Bolum 99',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1808'),
      'video-1808',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-1'),
      'Episode 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1797'),
      'video-1797',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-51'),
      'Episode 51',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1215'),
      'video-1215',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-1'),
      'Episode 1',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1196'),
      'video-1196',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-15'),
      'Episode 15',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1182'),
      'video-1182',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638710669.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1168'),
      'video-1168',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-13-part-1'),
      'Episode 13 · Part 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1152'),
      'video-1152',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638682464.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1313'),
      'video-1313',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1284'),
      'video-1284',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-1'),
      'Episode 1',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1138'),
      'video-1138',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-165'),
      'Episode 165',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1216'),
      'video-1216',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-10'),
      'Episode 10',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1220'),
      'video-1220',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-12'),
      'Episode 12',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-632'),
      'video-632',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-568'),
      'video-568',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613401145.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-567'),
      'video-567',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-1'),
      'Episode 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613399393.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-545'),
      'video-545',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-543'),
      'video-543',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-19'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-19-episode-120'),
      'Episode 120',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-512'),
      'video-512',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-89'),
      'Episode 89',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-478'),
      'video-478',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-55'),
      'Episode 55',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-407'),
      'video-407',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-18'),
      'Episode 18',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-390'),
      'video-390',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-330'),
      'video-330',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-1'),
      'Episode 1',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-287'),
      'video-287',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-1'),
      'Episode 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-182'),
      'video-182',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4083'),
      'video-4083',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-84'),
      'Episode 1 · Bolum 84',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1789365193.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4102'),
      'video-4102',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-87'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-87-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790673764.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4097'),
      'video-4097',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-84'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-84-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790387096.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4099'),
      'video-4099',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-83'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-83-bolum-186'),
      'Episode 2 · Bolum 186',
      7,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790527929.jpeg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3897'),
      'video-3897',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-1'),
      'Episode 1',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1760631349.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3887'),
      'video-3887',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-150'),
      'Episode 150',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1759076587.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3885'),
      'video-3885',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-51'),
      'Episode 51',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1758705744.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3261'),
      'video-3261',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-2'),
      'Episode 2',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3645'),
      'video-3645',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745156385.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3251'),
      'video-3251',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-29'),
      'Episode 29',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729610109.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3224'),
      'video-3224',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-165'),
      'Episode 165',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1727580304.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3225'),
      'video-3225',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-113'),
      'Episode 113',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1727658359.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3053'),
      'video-3053',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1719295988.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2923'),
      'video-2923',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-94'),
      'Episode 94',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1715074541.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2575'),
      'video-2575',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-2'),
      'Episode 2',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1700453222.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2540'),
      'video-2540',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-69'),
      'Episode 69',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698381395.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2404'),
      'video-2404',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      NULL,
      'Kurulus Osman Season 5: Behind the Scenes - Part 2',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1692462947.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2539'),
      'video-2539',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-81'),
      'Episode 81',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698597182.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1048'),
      'video-1048',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-2'),
      'Episode 2',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1001'),
      'video-1001',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-46'),
      'Episode 46',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-211'),
      'video-211',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-2'),
      'Episode 2',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-101'),
      'video-101',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-21'),
      'Episode 21',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-10'),
      'video-10',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-10'),
      'Episode 10',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3773'),
      'video-3773',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2451'),
      'video-2451',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-35'),
      'Episode 35',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2443'),
      'video-2443',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-23'),
      'Episode 23',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694089133.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2416'),
      'video-2416',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693571368.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2399'),
      'video-2399',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1691646650.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2372'),
      'video-2372',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2339'),
      'video-2339',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2126'),
      'video-2126',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-2'),
      'Episode 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1679938799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1898'),
      'video-1898',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-2'),
      'Episode 2',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1969'),
      'video-1969',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1865'),
      'video-1865',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-33'),
      'Episode 1 · Bolum 33',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860521.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1833'),
      'video-1833',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-50'),
      'Episode 50',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1816'),
      'video-1816',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-99'),
      'Episode 1 · Bolum 99',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1810'),
      'video-1810',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-2'),
      'Episode 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1798'),
      'video-1798',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-52'),
      'Episode 52',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1219'),
      'video-1219',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-2'),
      'Episode 2',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1197'),
      'video-1197',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-16'),
      'Episode 16',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1183'),
      'video-1183',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638710669.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1169'),
      'video-1169',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-13-part-2'),
      'Episode 13 · Part 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1153'),
      'video-1153',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638682464.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1315'),
      'video-1315',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1285'),
      'video-1285',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-1'),
      'Episode 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1206'),
      'video-1206',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-166'),
      'Episode 166',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1217'),
      'video-1217',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-10'),
      'Episode 10',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1221'),
      'video-1221',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-12'),
      'Episode 12',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-635'),
      'video-635',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-570'),
      'video-570',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613401145.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-587'),
      'video-587',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-2'),
      'Episode 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613399393.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-546'),
      'video-546',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-544'),
      'video-544',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-19'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-19-episode-121'),
      'Episode 121',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-513'),
      'video-513',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-90'),
      'Episode 90',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-479'),
      'video-479',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-56'),
      'Episode 56',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-408'),
      'video-408',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-19'),
      'Episode 19',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-391'),
      'video-391',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-331'),
      'video-331',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-2'),
      'Episode 2',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-288'),
      'video-288',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-2'),
      'Episode 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-183'),
      'video-183',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4092'),
      'video-4092',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-85'),
      'Episode 2 · Bolum 85',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790132744.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3907'),
      'video-3907',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1762392748.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3890'),
      'video-3890',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-151'),
      'Episode 151',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1759681054.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3888'),
      'video-3888',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-52'),
      'Episode 52 · Bolum 52',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1759251749.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3262'),
      'video-3262',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-3'),
      'Episode 3',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3646'),
      'video-3646',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-2'),
      'Episode 2',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745156385.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3257'),
      'video-3257',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-30'),
      'Episode 30',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1730136052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3227'),
      'video-3227',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-166'),
      'Episode 166',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1727917461.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3230'),
      'video-3230',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-114'),
      'Episode 114',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1728279504.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3058'),
      'video-3058',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1719407968.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2935'),
      'video-2935',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-95'),
      'Episode 95',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1715399616.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2576'),
      'video-2576',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-3'),
      'Episode 3',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1700453222.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2552'),
      'video-2552',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-70'),
      'Episode 70',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698381395.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2405'),
      'video-2405',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      NULL,
      'Kurulus Osman Season 5: Behind the Scenes - Part 3',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1692505379.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2541'),
      'video-2541',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-82'),
      'Episode 82',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698597182.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1049'),
      'video-1049',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-3'),
      'Episode 3',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1002'),
      'video-1002',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-47'),
      'Episode 47',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-212'),
      'video-212',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-3'),
      'Episode 3',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-102'),
      'video-102',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-22'),
      'Episode 22',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-11'),
      'video-11',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-11'),
      'Episode 11',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3774'),
      'video-3774',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2452'),
      'video-2452',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-36'),
      'Episode 36',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2453'),
      'video-2453',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-24'),
      'Episode 24',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694089133.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2419'),
      'video-2419',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693915247.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2409'),
      'video-2409',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-49'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-49-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1691646650.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2378'),
      'video-2378',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2348'),
      'video-2348',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2150'),
      'video-2150',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-3'),
      'Episode 3',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1679938799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1899'),
      'video-1899',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-3'),
      'Episode 3',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1985'),
      'video-1985',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1904'),
      'video-1904',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-34'),
      'Episode 2 · Bolum 34',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1834'),
      'video-1834',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-51'),
      'Episode 51',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1817'),
      'video-1817',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-100'),
      'Episode 2 · Bolum 100',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1813'),
      'video-1813',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-3'),
      'Episode 3',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1799'),
      'video-1799',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-53'),
      'Episode 53',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1222'),
      'video-1222',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-3'),
      'Episode 3',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1198'),
      'video-1198',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-17'),
      'Episode 17',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1184'),
      'video-1184',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-32'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-32-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638710669.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1170'),
      'video-1170',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-14-part-1'),
      'Episode 14 · Part 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1154'),
      'video-1154',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638682464.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1317'),
      'video-1317',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1286'),
      'video-1286',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-2'),
      'Episode 2',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1208'),
      'video-1208',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-167'),
      'Episode 167',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1218'),
      'video-1218',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-11'),
      'Episode 11',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1235'),
      'video-1235',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-13'),
      'Episode 13',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-636'),
      'video-636',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-576'),
      'video-576',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-22'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-22-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613401145.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-588'),
      'video-588',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-3'),
      'Episode 3',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613399393.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-547'),
      'video-547',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-514'),
      'video-514',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-91'),
      'Episode 91',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-480'),
      'video-480',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-57'),
      'Episode 57',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-409'),
      'video-409',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-20'),
      'Episode 20',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-392'),
      'video-392',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-332'),
      'video-332',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-3'),
      'Episode 3',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-289'),
      'video-289',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-3'),
      'Episode 3',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-184'),
      'video-184',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-40922'),
      'video-40922',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-82'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-82-bolum-86'),
      'Episode 3 · Bolum 86',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1790680272.png'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3908'),
      'video-3908',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-2'),
      'Episode 2',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1762393192.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3893'),
      'video-3893',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-152'),
      'Episode 152',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1760285732.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3889'),
      'video-3889',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-52'),
      'Episode 52',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1759252086.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3263'),
      'video-3263',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-4'),
      'Episode 4',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3647'),
      'video-3647',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-72'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-72-episode-3'),
      'Episode 3',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745156385.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3258'),
      'video-3258',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-30'),
      'Episode 30',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1730136368.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3234'),
      'video-3234',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-166'),
      'Episode 166',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1728490734.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3237'),
      'video-3237',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-115'),
      'Episode 115',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1728837930.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3073'),
      'video-3073',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-4'),
      'Episode 4',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1720179604.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2960'),
      'video-2960',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-96'),
      'Episode 96',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1716032936.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2579'),
      'video-2579',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-4'),
      'Episode 4',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1700453222.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2557'),
      'video-2557',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-71'),
      'Episode 71',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1698381395.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2408'),
      'video-2408',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      NULL,
      'Kurulus Osman Season 5 - Behind the Scenes Part 4',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1692880883.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2549'),
      'video-2549',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-83'),
      'Episode 83',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1699842692.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1050'),
      'video-1050',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-4'),
      'Episode 4',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1003'),
      'video-1003',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-48'),
      'Episode 48',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-213'),
      'video-213',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-4'),
      'Episode 4',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-103'),
      'video-103',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-23'),
      'Episode 23',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-12'),
      'video-12',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-12'),
      'Episode 12',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3775'),
      'video-3775',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-4'),
      'Episode 4',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2454'),
      'video-2454',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-37'),
      'Episode 37',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    )
ON CONFLICT (source_id) DO UPDATE SET
  display_label = CASE WHEN video_variants.updated_at > video_variants.created_at THEN video_variants.display_label ELSE EXCLUDED.display_label END,
  languages = EXCLUDED.languages,
  version = EXCLUDED.version,
  thumbnail_url = EXCLUDED.thumbnail_url,
  publication_state = CASE WHEN video_variants.collection_id = extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:collection-68') THEN 'published' ELSE video_variants.publication_state END,
  updated_at = now();