INSERT INTO public.video_variants (id, source_id, collection_id, group_id, display_label, reported_season, languages, version, publication_state, duration_seconds, thumbnail_url)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1972'),
      'video-1972',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-63'),
      'Episode 63',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1870'),
      'video-1870',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-106'),
      'Episode 8 · Bolum 106',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1896'),
      'video-1896',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-39'),
      'Episode 12 · Bolum 39',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1831'),
      'video-1831',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-65'),
      'Episode 65',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1322'),
      'video-1322',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-15'),
      'Episode 15',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1357'),
      'video-1357',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-29'),
      'Episode 29',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1207'),
      'video-1207',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-24'),
      'Episode 24',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1166'),
      'video-1166',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-12-part-1'),
      'Episode 12 · Part 1',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638682464.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1571'),
      'video-1571',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-15'),
      'Episode 15',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1336'),
      'video-1336',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-8'),
      'Episode 8',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-817'),
      'video-817',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-10'),
      'Episode 10',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1463'),
      'video-1463',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-17'),
      'Episode 17',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1469'),
      'video-1469',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-19'),
      'Episode 19',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-648'),
      'video-648',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-15'),
      'Episode 15',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-600'),
      'video-600',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-21'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-21-episode-15'),
      'Episode 15',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613399393.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-559'),
      'video-559',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-15'),
      'Episode 15',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-526'),
      'video-526',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-103'),
      'Episode 103',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-492'),
      'video-492',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-69'),
      'Episode 69',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-421'),
      'video-421',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-31'),
      'Episode 31',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-404'),
      'video-404',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-15'),
      'Episode 15',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-344'),
      'video-344',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-15'),
      'Episode 15',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-301'),
      'video-301',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-15'),
      'Episode 15',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-196'),
      'video-196',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-15'),
      'Episode 15',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3937'),
      'video-3937',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-8'),
      'Episode 8 · Bolum 8',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1765985250.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3947'),
      'video-3947',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-164'),
      'Episode 164 · Bolum 164',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1768141733.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3911'),
      'video-3911',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-58'),
      'Episode 58',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1762882444.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3314'),
      'video-3314',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-16'),
      'Episode 16',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3387'),
      'video-3387',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-36'),
      'Episode 36',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1733758153.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3299'),
      'video-3299',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-172'),
      'Episode 172',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1732718656.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3432'),
      'video-3432',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-127'),
      'Episode 127',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1736128672.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3155'),
      'video-3155',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1722221924.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3171'),
      'video-3171',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-108'),
      'Episode 108',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1723364263.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2603'),
      'video-2603',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-16'),
      'Episode 16',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1702392107.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2714'),
      'video-2714',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-83'),
      'Episode 83',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1707715760.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2546'),
      'video-2546',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-136'),
      'Episode 136',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1699530004.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2713'),
      'video-2713',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-95'),
      'Episode 95',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1707711224.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1062'),
      'video-1062',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-16'),
      'Episode 16',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1015'),
      'video-1015',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-60'),
      'Episode 60',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-225'),
      'video-225',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-16'),
      'Episode 16',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-115'),
      'video-115',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-35'),
      'Episode 35',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-23'),
      'video-23',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-23'),
      'Episode 23',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3789'),
      'video-3789',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2500'),
      'video-2500',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-49'),
      'Episode 49',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2628'),
      'video-2628',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-37'),
      'Episode 37',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703317561.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2435'),
      'video-2435',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693917709.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2396'),
      'video-2396',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2868'),
      'video-2868',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-16'),
      'Episode 16',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2369'),
      'video-2369',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-16'),
      'Episode 16',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1679938799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1928'),
      'video-1928',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-16'),
      'Episode 16',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2282'),
      'video-2282',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2037'),
      'video-2037',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-40'),
      'Episode 8 · Bolum 40',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1987'),
      'video-1987',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-64'),
      'Episode 64',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1871'),
      'video-1871',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-106'),
      'Episode 8 · Bolum 106',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1897'),
      'video-1897',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-39'),
      'Episode 12 · Bolum 39',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1842'),
      'video-1842',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-66'),
      'Episode 66',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1326'),
      'video-1326',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-16'),
      'Episode 16',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1386'),
      'video-1386',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-30'),
      'Episode 30',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1224'),
      'video-1224',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-25'),
      'Episode 25',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1167'),
      'video-1167',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-30'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-30-episode-12-part-2'),
      'Episode 12 · Part 2',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638682464.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1587'),
      'video-1587',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1338'),
      'video-1338',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-8'),
      'Episode 8',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-818'),
      'video-818',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-11'),
      'Episode 11',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1466'),
      'video-1466',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-17'),
      'Episode 17',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1470'),
      'video-1470',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-19'),
      'Episode 19',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-649'),
      'video-649',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-560'),
      'video-560',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-527'),
      'video-527',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-104'),
      'Episode 104',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-493'),
      'video-493',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-70'),
      'Episode 70',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-422'),
      'video-422',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-32'),
      'Episode 32',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-405'),
      'video-405',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-345'),
      'video-345',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-16'),
      'Episode 16',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-302'),
      'video-302',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-16'),
      'Episode 16',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-197'),
      'video-197',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-16'),
      'Episode 16',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3941'),
      'video-3941',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-9'),
      'Episode 9 · Bolum 9',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1766589428.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3950'),
      'video-3950',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-165'),
      'Episode 165 · Bolum 165',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1768750790.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3916'),
      'video-3916',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-59'),
      'Episode 59',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1763491084.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3315'),
      'video-3315',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-17'),
      'Episode 17',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3412'),
      'video-3412',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-37'),
      'Episode 37',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1734366276.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3305'),
      'video-3305',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-173'),
      'Episode 173',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1733241693.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3473'),
      'video-3473',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-128'),
      'Episode 128',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1737276702.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3162'),
      'video-3162',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1722594912.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3172'),
      'video-3172',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-109'),
      'Episode 109',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1723364718.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2604'),
      'video-2604',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-17'),
      'Episode 17',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703083016.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2734'),
      'video-2734',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-84'),
      'Episode 84',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1708499292.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2547'),
      'video-2547',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-136'),
      'Bolum 136',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1699532925.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2729'),
      'video-2729',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-96'),
      'Episode 96',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1708273871.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1063'),
      'video-1063',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-17'),
      'Episode 17',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1016'),
      'video-1016',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-61'),
      'Episode 61',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-226'),
      'video-226',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-17'),
      'Episode 17',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-116'),
      'video-116',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-36'),
      'Episode 36',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-24'),
      'video-24',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3791'),
      'video-3791',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-20'),
      'Episode 20',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2501'),
      'video-2501',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-50'),
      'Episode 50',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2647'),
      'video-2647',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-38'),
      'Episode 38',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1705216756.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2436'),
      'video-2436',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693917709.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2397'),
      'video-2397',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2869'),
      'video-2869',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-17'),
      'Episode 17',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2379'),
      'video-2379',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-46'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-46-episode-17'),
      'Episode 17',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1679938799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1929'),
      'video-1929',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-17'),
      'Episode 17',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2291'),
      'video-2291',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2038'),
      'video-2038',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-41'),
      'Episode 9 · Bolum 41',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2021'),
      'video-2021',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-65'),
      'Episode 65',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1873'),
      'video-1873',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-107'),
      'Episode 9 · Bolum 107',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1911'),
      'video-1911',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-40'),
      'Episode 13 · Bolum 40',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1844'),
      'video-1844',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-67'),
      'Episode 67',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1331'),
      'video-1331',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-17'),
      'Episode 17',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1405'),
      'video-1405',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-31'),
      'Episode 31',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1240'),
      'video-1240',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-26'),
      'Episode 26',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1604'),
      'video-1604',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1389'),
      'video-1389',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-9'),
      'Episode 9',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-819'),
      'video-819',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-12'),
      'Episode 12',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1490'),
      'video-1490',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-18'),
      'Episode 18',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1494'),
      'video-1494',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-20'),
      'Episode 20',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-650'),
      'video-650',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-561'),
      'video-561',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-528'),
      'video-528',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-105'),
      'Episode 105',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-494'),
      'video-494',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-71'),
      'Episode 71',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-423'),
      'video-423',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-33-part-1'),
      'Episode 33 · Part 1',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-406'),
      'video-406',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-11'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-11-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-346'),
      'video-346',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-17'),
      'Episode 17',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-303'),
      'video-303',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-17'),
      'Episode 17',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-198'),
      'video-198',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-17'),
      'Episode 17',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3942'),
      'video-3942',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-9'),
      'Episode 9 · Bolum 9',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1766589667.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3955'),
      'video-3955',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-166'),
      'Episode 166 · Bolum 166',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1769395043.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3917'),
      'video-3917',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-59'),
      'Episode 59',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1763491393.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3316'),
      'video-3316',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-18'),
      'Episode 18',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3413'),
      'video-3413',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-37'),
      'Episode 37',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1734366757.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3306'),
      'video-3306',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-173'),
      'Episode 173',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1733327990.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3480'),
      'video-3480',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-129'),
      'Episode 129',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1737911027.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3169'),
      'video-3169',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1722937229.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3176'),
      'video-3176',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-110'),
      'Episode 110',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1723881277.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2605'),
      'video-2605',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-18'),
      'Episode 18',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703167234.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2740'),
      'video-2740',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-85'),
      'Episode 85',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1708774143.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2558'),
      'video-2558',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-137'),
      'Episode 137',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1699530004.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2747'),
      'video-2747',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-97'),
      'Episode 97',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1708887935.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1064'),
      'video-1064',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-18'),
      'Episode 18',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1017'),
      'video-1017',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-62'),
      'Episode 62',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-227'),
      'video-227',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-18'),
      'Episode 18',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-117'),
      'video-117',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-37'),
      'Episode 37',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-25'),
      'video-25',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3793'),
      'video-3793',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-22'),
      'Episode 22',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2502'),
      'video-2502',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-51'),
      'Episode 51',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2660'),
      'video-2660',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-39'),
      'Episode 39',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1705812912.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2437'),
      'video-2437',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693917709.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2398'),
      'video-2398',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2870'),
      'video-2870',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-18'),
      'Episode 18',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1931'),
      'video-1931',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-18'),
      'Episode 18',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2309'),
      'video-2309',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2039'),
      'video-2039',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-41'),
      'Episode 9 · Bolum 41',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2041'),
      'video-2041',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-66'),
      'Episode 66',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1874'),
      'video-1874',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-107'),
      'Episode 9 · Bolum 107',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1912'),
      'video-1912',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-40'),
      'Episode 13 · Bolum 40',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1847'),
      'video-1847',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-68'),
      'Episode 68',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1332'),
      'video-1332',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-18'),
      'Episode 18',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1426'),
      'video-1426',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-32'),
      'Episode 32',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1333'),
      'video-1333',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-27'),
      'Episode 27',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1620'),
      'video-1620',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1391'),
      'video-1391',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-9'),
      'Episode 9',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-820'),
      'video-820',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-13'),
      'Episode 13',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1491'),
      'video-1491',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-18'),
      'Episode 18',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1495'),
      'video-1495',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-20'),
      'Episode 20',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-651'),
      'video-651',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-562'),
      'video-562',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-20'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-20-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613398645.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-529'),
      'video-529',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-106'),
      'Episode 106',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-495'),
      'video-495',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-72'),
      'Episode 72',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-424'),
      'video-424',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-33-part-2'),
      'Episode 33 · Part 2',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-347'),
      'video-347',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-18'),
      'Episode 18',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-304'),
      'video-304',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-18'),
      'Episode 18',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-199'),
      'video-199',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-18'),
      'Episode 18',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3944'),
      'video-3944',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-10'),
      'Episode 10 · Bolum 10',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1767252628.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3960'),
      'video-3960',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-bolum-167'),
      'Episode 167 · Bolum 167',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1769961561.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3924'),
      'video-3924',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-60'),
      'Episode 60',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1764687648.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3317'),
      'video-3317',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-19'),
      'Episode 19',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3419'),
      'video-3419',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-38'),
      'Episode 38',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1734967382.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3390'),
      'video-3390',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-174'),
      'Episode 174',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1733935717.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3483'),
      'video-3483',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-130'),
      'Episode 130',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1738511379.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3174'),
      'video-3174',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-19'),
      'Episode 19',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1723809090.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3177'),
      'video-3177',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-111'),
      'Episode 111',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1723949887.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2606'),
      'video-2606',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-19'),
      'Episode 19',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2764'),
      'video-2764',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-86'),
      'Episode 86',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1709486799.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2559'),
      'video-2559',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-137'),
      'Episode 137',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1699532925.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2765'),
      'video-2765',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-98'),
      'Episode 98',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1709522603.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1065'),
      'video-1065',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-19'),
      'Episode 19',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1018'),
      'video-1018',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-63'),
      'Episode 63',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-228'),
      'video-228',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-19'),
      'Episode 19',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-118'),
      'video-118',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-38'),
      'Episode 38',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-26'),
      'video-26',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3795'),
      'video-3795',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2503'),
      'video-2503',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-52'),
      'Episode 52',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2671'),
      'video-2671',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-40'),
      'Episode 40',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706341575.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2438'),
      'video-2438',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-51'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-51-episode-19'),
      'Episode 19',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1693917709.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2401'),
      'video-2401',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-19'),
      'Episode 19',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2871'),
      'video-2871',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-47'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-47-episode-19'),
      'Episode 19',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1687688052.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1932'),
      'video-1932',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-19'),
      'Episode 19',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2325'),
      'video-2325',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-42'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-42-episode-19'),
      'Episode 19',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1670141819.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2055'),
      'video-2055',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-42'),
      'Episode 10 · Bolum 42',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2059'),
      'video-2059',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-67'),
      'Episode 67',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1876'),
      'video-1876',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-108'),
      'Episode 10 · Bolum 108',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1926'),
      'video-1926',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-41'),
      'Episode 14 · Bolum 41',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1860'),
      'video-1860',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-69'),
      'Episode 69',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    )
ON CONFLICT (source_id) DO UPDATE SET
  display_label = CASE WHEN video_variants.updated_at > video_variants.created_at THEN video_variants.display_label ELSE EXCLUDED.display_label END,
  languages = EXCLUDED.languages,
  version = EXCLUDED.version,
  thumbnail_url = EXCLUDED.thumbnail_url,
  publication_state = CASE WHEN video_variants.collection_id = extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:collection-68') THEN 'published' ELSE video_variants.publication_state END,
  updated_at = now();