INSERT INTO public.video_variants (id, source_id, collection_id, group_id, display_label, reported_season, languages, version, publication_state, duration_seconds, thumbnail_url)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1095'),
      'video-1095',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-49'),
      'Episode 49',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-692'),
      'video-692',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-2'),
      'Episode 2',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-258'),
      'video-258',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-49'),
      'Episode 49',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-148'),
      'video-148',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-68'),
      'Episode 68',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-53'),
      'video-53',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-53'),
      'Episode 53',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3825'),
      'video-3825',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-54'),
      'Episode 54',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1995'),
      'video-1995',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-49'),
      'Episode 49',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2199'),
      'video-2199',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-123'),
      'Bolum 123',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2247'),
      'video-2247',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-56'),
      'Episode 29 · Bolum 56',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1409'),
      'video-1409',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-49'),
      'Episode 49',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1708'),
      'video-1708',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-25'),
      'Episode 25',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-854'),
      'video-854',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-44'),
      'Episode 44',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1772'),
      'video-1772',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-34'),
      'Episode 34',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-745'),
      'video-745',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-4'),
      'Episode 4',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-786'),
      'video-786',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-49'),
      'Episode 49',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-378'),
      'video-378',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-49'),
      'Episode 49',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4039'),
      'video-4039',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-25'),
      'Episode 25',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1780021512.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4013'),
      'video-4013',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-76'),
      'Episode 76',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1776190055.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3441'),
      'video-3441',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-50'),
      'Episode 50',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3655'),
      'video-3655',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-53'),
      'Episode 53',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745253927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3659'),
      'video-3659',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-188'),
      'Episode 188',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745429458.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2664'),
      'video-2664',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-50'),
      'Episode 50',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1705764782.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2805'),
      'video-2805',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-153'),
      'Episode 153',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1710952684.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1096'),
      'video-1096',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-50'),
      'Episode 50',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-693'),
      'video-693',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-3'),
      'Episode 3',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-259'),
      'video-259',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-50'),
      'Episode 50',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-149'),
      'video-149',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-69'),
      'Episode 69',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-54'),
      'video-54',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-54'),
      'Episode 54',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3826'),
      'video-3826',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-55'),
      'Episode 55',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1996'),
      'video-1996',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-50'),
      'Episode 50',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2200'),
      'video-2200',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-123'),
      'Bolum 123',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2248'),
      'video-2248',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-56'),
      'Episode 29 · Bolum 56',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1413'),
      'video-1413',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-50'),
      'Episode 50',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1709'),
      'video-1709',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-855'),
      'video-855',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-45'),
      'Episode 45',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1773'),
      'video-1773',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-34'),
      'Episode 34',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-746'),
      'video-746',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-4'),
      'Episode 4',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-787'),
      'video-787',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-50'),
      'Episode 50',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-379'),
      'video-379',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-50'),
      'Episode 50',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4044'),
      'video-4044',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1781147414.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4014'),
      'video-4014',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-76'),
      'Episode 76',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1776190222.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3442'),
      'video-3442',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-51'),
      'Episode 51',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3661'),
      'video-3661',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-54'),
      'Episode 54',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1745861026.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3665'),
      'video-3665',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-190'),
      'Episode 190',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1746028956.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2667'),
      'video-2667',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-51'),
      'Episode 51',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1705764782.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2806'),
      'video-2806',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-153'),
      'Episode 153',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1710952967.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1097'),
      'video-1097',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-51'),
      'Episode 51',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-694'),
      'video-694',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-4'),
      'Episode 4',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-260'),
      'video-260',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-51'),
      'Episode 51',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-150'),
      'video-150',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-70'),
      'Episode 70',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-55'),
      'video-55',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-55'),
      'Episode 55',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3827'),
      'video-3827',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-56'),
      'Episode 56',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1997'),
      'video-1997',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-51'),
      'Episode 51',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2217'),
      'video-2217',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-124'),
      'Bolum 124',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2270'),
      'video-2270',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-57'),
      'Episode 30 · Bolum 57',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1417'),
      'video-1417',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-51'),
      'Episode 51',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1725'),
      'video-1725',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-26'),
      'Episode 26',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-856'),
      'video-856',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-46'),
      'Episode 46',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-738'),
      'video-738',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-1'),
      'Episode 1',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-752'),
      'video-752',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-5'),
      'Episode 5',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-788'),
      'video-788',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-51'),
      'Episode 51',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-380'),
      'video-380',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-51'),
      'Episode 51',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4045'),
      'video-4045',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-episode-26'),
      'Episode 26',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1781148093.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4018'),
      'video-4018',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-77'),
      'Episode 77',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1776788723.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3443'),
      'video-3443',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-52'),
      'Episode 52',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3662'),
      'video-3662',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-54'),
      'Episode 54',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1745861307.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3666'),
      'video-3666',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-190'),
      'Episode 190',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1746029374.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2668'),
      'video-2668',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-52'),
      'Episode 52',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1705764782.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2822'),
      'video-2822',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-154'),
      'Episode 154',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1711555424.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1098'),
      'video-1098',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-52'),
      'Episode 52',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-695'),
      'video-695',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-5'),
      'Episode 5',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-261'),
      'video-261',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-52'),
      'Episode 52',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-151'),
      'video-151',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-71'),
      'Episode 71',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-56'),
      'video-56',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-56'),
      'Episode 56',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3828'),
      'video-3828',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-57'),
      'Episode 57',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1998'),
      'video-1998',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-52'),
      'Episode 52',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2218'),
      'video-2218',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-124'),
      'Bolum 124',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2271'),
      'video-2271',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-57'),
      'Episode 30 · Bolum 57',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1420'),
      'video-1420',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-52'),
      'Episode 52',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1726'),
      'video-1726',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-857'),
      'video-857',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-47'),
      'Episode 47',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-744'),
      'video-744',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-1'),
      'Episode 1',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-753'),
      'video-753',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-5'),
      'Episode 5',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-789'),
      'video-789',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-52'),
      'Episode 52',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-381'),
      'video-381',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-52'),
      'Episode 52',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4019'),
      'video-4019',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-77'),
      'Episode 77',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1776789016.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3444'),
      'video-3444',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-53'),
      'Episode 53',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3668'),
      'video-3668',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-55'),
      'Episode 55',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1746463977.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3672'),
      'video-3672',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-191'),
      'Episode 191',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1746626565.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2669'),
      'video-2669',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-53'),
      'Episode 53',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2823'),
      'video-2823',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-154'),
      'Episode 154',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1711556230.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1099'),
      'video-1099',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-53'),
      'Episode 53',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-696'),
      'video-696',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-6'),
      'Episode 6',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-262'),
      'video-262',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-53'),
      'Episode 53',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-152'),
      'video-152',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-72'),
      'Episode 72',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-57'),
      'video-57',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-57'),
      'Episode 57',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3829'),
      'video-3829',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-58'),
      'Episode 58',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2000'),
      'video-2000',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-53'),
      'Episode 53',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2234'),
      'video-2234',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-125'),
      'Bolum 125',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2296'),
      'video-2296',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-58'),
      'Episode 58',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1421'),
      'video-1421',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-53'),
      'Episode 53',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1741'),
      'video-1741',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-27'),
      'Episode 27',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-858'),
      'video-858',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-48'),
      'Episode 48',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-748'),
      'video-748',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-2'),
      'Episode 2',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-756'),
      'video-756',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-6'),
      'Episode 6',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-790'),
      'video-790',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-53'),
      'Episode 53',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-382'),
      'video-382',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-53'),
      'Episode 53',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4020'),
      'video-4020',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-78'),
      'Episode 78',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1777427020.jpeg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3445'),
      'video-3445',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-54'),
      'Episode 54',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3669'),
      'video-3669',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-bolum-55'),
      'Episode 55 · Bolum 55',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1746465680.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3673'),
      'video-3673',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-191'),
      'Episode 191',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1746627140.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2670'),
      'video-2670',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-54'),
      'Episode 54',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2838'),
      'video-2838',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-155'),
      'Episode 155',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712163343.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1100'),
      'video-1100',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-54'),
      'Episode 54',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-697'),
      'video-697',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-7'),
      'Episode 7',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-263'),
      'video-263',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-54'),
      'Episode 54',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-153'),
      'video-153',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-73'),
      'Episode 73',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-58'),
      'video-58',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-58'),
      'Episode 58',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3830'),
      'video-3830',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-59'),
      'Episode 59',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2001'),
      'video-2001',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-54'),
      'Episode 54',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2235'),
      'video-2235',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-125'),
      'Bolum 125',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2297'),
      'video-2297',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-58'),
      'Episode 58',
      2,
      '{"Urdu","English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1423'),
      'video-1423',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-54'),
      'Episode 54',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1742'),
      'video-1742',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-859'),
      'video-859',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-49'),
      'Episode 49',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-749'),
      'video-749',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-2'),
      'Episode 2',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-757'),
      'video-757',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-6'),
      'Episode 6',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-791'),
      'video-791',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-54'),
      'Episode 54',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-383'),
      'video-383',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-54'),
      'Episode 54',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4021'),
      'video-4021',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-78'),
      'Episode 78',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1777427994.jpeg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3446'),
      'video-3446',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-55'),
      'Episode 55',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3675'),
      'video-3675',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-56'),
      'Episode 56',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1747058109.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3677'),
      'video-3677',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-192'),
      'Episode 192',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1747232103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2672'),
      'video-2672',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-55'),
      'Episode 55',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2839'),
      'video-2839',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-155'),
      'Episode 155',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712163789.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1101'),
      'video-1101',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-55'),
      'Episode 55',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-698'),
      'video-698',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-8'),
      'Episode 8',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-264'),
      'video-264',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-55'),
      'Episode 55',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-154'),
      'video-154',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-74'),
      'Episode 74',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-59'),
      'video-59',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-59'),
      'Episode 59',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3831'),
      'video-3831',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-60'),
      'Episode 60',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2002'),
      'video-2002',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-55'),
      'Episode 55',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2251'),
      'video-2251',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-episode-126'),
      'Episode 126',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2312'),
      'video-2312',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-59'),
      'Episode 59',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1427'),
      'video-1427',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-55'),
      'Episode 55',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-860'),
      'video-860',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-50'),
      'Episode 50',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-754'),
      'video-754',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-3'),
      'Episode 3',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-760'),
      'video-760',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-7'),
      'Episode 7',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-792'),
      'video-792',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-55'),
      'Episode 55',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-384'),
      'video-384',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-55'),
      'Episode 55',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4023'),
      'video-4023',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-79'),
      'Episode 79',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1778029388.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3447'),
      'video-3447',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-56'),
      'Episode 56',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3676'),
      'video-3676',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-56'),
      'Episode 56',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1747058438.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3678'),
      'video-3678',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-192'),
      'Episode 192',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1747232731.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2673'),
      'video-2673',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-56'),
      'Episode 56',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2855'),
      'video-2855',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-156'),
      'Episode 156',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712767754.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1102'),
      'video-1102',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-56'),
      'Episode 56',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-699'),
      'video-699',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-9'),
      'Episode 9',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-265'),
      'video-265',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-56'),
      'Episode 56',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-155'),
      'video-155',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-75'),
      'Episode 75',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-6'),
      'video-6',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-6'),
      'Episode 6',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3832'),
      'video-3832',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-61'),
      'Episode 61',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2003'),
      'video-2003',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-56'),
      'Episode 56',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2252'),
      'video-2252',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-episode-126'),
      'Episode 126',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2313'),
      'video-2313',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-59'),
      'Episode 59',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1430'),
      'video-1430',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-56'),
      'Episode 56',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-861'),
      'video-861',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-51'),
      'Episode 51',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-755'),
      'video-755',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-3'),
      'Episode 3',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-761'),
      'video-761',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-7'),
      'Episode 7',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-793'),
      'video-793',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-56'),
      'Episode 56',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-385'),
      'video-385',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-56'),
      'Episode 56',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4024'),
      'video-4024',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-79'),
      'Episode 79',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1778030369.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3448'),
      'video-3448',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-57'),
      'Episode 57',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3680'),
      'video-3680',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-57'),
      'Episode 57',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1747671463.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3689'),
      'video-3689',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-193'),
      'Episode 193',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1748454865.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2676'),
      'video-2676',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-57'),
      'Episode 57',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2856'),
      'video-2856',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-156'),
      'Episode 156',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712803461.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1103'),
      'video-1103',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-57'),
      'Episode 57',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-700'),
      'video-700',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-10'),
      'Episode 10',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-266'),
      'video-266',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-57'),
      'Episode 57',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-156'),
      'video-156',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-76'),
      'Episode 76',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-60'),
      'video-60',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-60'),
      'Episode 60',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3833'),
      'video-3833',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-62'),
      'Episode 62',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2004'),
      'video-2004',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-57'),
      'Episode 57',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2264'),
      'video-2264',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-episode-127'),
      'Episode 127',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2331'),
      'video-2331',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-episode-60'),
      'Episode 60',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1436'),
      'video-1436',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-57'),
      'Episode 57',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-862'),
      'video-862',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-52'),
      'Episode 52',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-758'),
      'video-758',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-4'),
      'Episode 4',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-766'),
      'video-766',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-8'),
      'Episode 8',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-794'),
      'video-794',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-57'),
      'Episode 57',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-386'),
      'video-386',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-57'),
      'Episode 57',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4028'),
      'video-4028',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-episode-80'),
      'Episode 80',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1778634801.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3449'),
      'video-3449',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-58'),
      'Episode 58',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3681'),
      'video-3681',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-57'),
      'Episode 57',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1747671886.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3690'),
      'video-3690',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-193'),
      'Episode 193',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1748455268.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2690'),
      'video-2690',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-58'),
      'Episode 58',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2895'),
      'video-2895',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-157'),
      'Episode 157',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713974931.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1104'),
      'video-1104',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-58'),
      'Episode 58',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-701'),
      'video-701',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-11'),
      'Episode 11',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    )
ON CONFLICT (source_id) DO UPDATE SET
  display_label = CASE WHEN video_variants.updated_at > video_variants.created_at THEN video_variants.display_label ELSE EXCLUDED.display_label END,
  languages = EXCLUDED.languages,
  version = EXCLUDED.version,
  thumbnail_url = EXCLUDED.thumbnail_url,
  publication_state = CASE WHEN video_variants.collection_id = extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:collection-68') THEN 'published' ELSE video_variants.publication_state END,
  updated_at = now();