INSERT INTO public.video_variants (id, source_id, collection_id, group_id, display_label, reported_season, languages, version, publication_state, duration_seconds, thumbnail_url)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3424'),
      'video-3424',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-176'),
      'Episode 176',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1735154659.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3560'),
      'video-3560',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-135'),
      'Episode 135',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1741537355.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3211'),
      'video-3211',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726053110.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3206'),
      'video-3206',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-116'),
      'Episode 116',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1725679630.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2617'),
      'video-2617',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-24'),
      'Episode 24',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2848'),
      'video-2848',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-91'),
      'Episode 91',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712661479.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2589'),
      'video-2589',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-140'),
      'Episode 140',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1702309693.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2862'),
      'video-2862',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-103'),
      'Episode 103',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713112505.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1070'),
      'video-1070',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-24'),
      'Episode 24',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1023'),
      'video-1023',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-68'),
      'Episode 68',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-233'),
      'video-233',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-24'),
      'Episode 24',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-123'),
      'video-123',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-43'),
      'Episode 43',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-30'),
      'video-30',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-30'),
      'Episode 30',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3800'),
      'video-3800',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-29'),
      'Episode 29',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2509'),
      'video-2509',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-57'),
      'Episode 57',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2827'),
      'video-2827',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-45'),
      'Episode 45',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1711813891.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2411'),
      'video-2411',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1945'),
      'video-1945',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-24'),
      'Episode 24',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2117'),
      'video-2117',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-44'),
      'Episode 12 · Bolum 44',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2171'),
      'video-2171',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-72'),
      'Episode 72',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1900'),
      'video-1900',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-110'),
      'Episode 12 · Bolum 110',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1959'),
      'video-1959',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-43'),
      'Episode 16 · Bolum 43',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1894'),
      'video-1894',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-74'),
      'Episode 74',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1354'),
      'video-1354',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-24'),
      'Episode 24',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1564'),
      'video-1564',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-38'),
      'Episode 38',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1449'),
      'video-1449',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-33'),
      'Episode 33',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1729'),
      'video-1729',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1456'),
      'video-1456',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-12'),
      'Episode 12',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-826'),
      'video-826',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-19'),
      'Episode 19',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1555'),
      'video-1555',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-21'),
      'Episode 21',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1558'),
      'video-1558',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-23'),
      'Episode 23',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-668'),
      'video-668',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-535'),
      'video-535',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-112'),
      'Episode 112',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-501'),
      'video-501',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-78'),
      'Episode 78',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-430'),
      'video-430',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-38'),
      'Episode 38',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-353'),
      'video-353',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-24'),
      'Episode 24',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-583'),
      'video-583',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-24'),
      'Episode 24',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613630045.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-205'),
      'video-205',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3963'),
      'video-3963',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-13'),
      'Episode 13 · Bolum 13',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1770135714.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3994'),
      'video-3994',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-173'),
      'Episode 173',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1773594344.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3939'),
      'video-3939',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-63'),
      'Episode 63 · Bolum 63',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1766508050.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3323'),
      'video-3323',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-25'),
      'Episode 25',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3474'),
      'video-3474',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-41'),
      'Episode 41',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1737391010.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3430'),
      'video-3430',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-177'),
      'Episode 177',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1735744805.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3567'),
      'video-3567',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-136'),
      'Episode 136',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1742146702.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3215'),
      'video-3215',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726646805.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3209'),
      'video-3209',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-117'),
      'Episode 117',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1725793603.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2619'),
      'video-2619',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-25'),
      'Episode 25',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2853'),
      'video-2853',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-59'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-59-episode-92'),
      'Episode 92',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712750651.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2590'),
      'video-2590',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-140'),
      'Episode 140',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1702310479.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2886'),
      'video-2886',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-104'),
      'Episode 104',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713717527.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1071'),
      'video-1071',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-25'),
      'Episode 25',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1024'),
      'video-1024',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-69'),
      'Episode 69',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-234'),
      'video-234',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-25'),
      'Episode 25',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-124'),
      'video-124',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-44'),
      'Episode 44',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-31'),
      'video-31',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-31'),
      'Episode 31',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3801'),
      'video-3801',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-30'),
      'Episode 30',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2510'),
      'video-2510',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-58'),
      'Episode 58',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2849'),
      'video-2849',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-46'),
      'Episode 46',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1712664177.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2412'),
      'video-2412',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1948'),
      'video-1948',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-25'),
      'Episode 25',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2140'),
      'video-2140',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-45'),
      'Episode 13 · Bolum 45',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2193'),
      'video-2193',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-73'),
      'Episode 73',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1901'),
      'video-1901',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-111'),
      'Episode 13 · Bolum 111',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1974'),
      'video-1974',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      NULL,
      'Unavailable record 1974',
      NULL,
      '{}',
      'subtitled',
      'draft',
      NULL,
      NULL
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1909'),
      'video-1909',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-75'),
      'Episode 75',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1355'),
      'video-1355',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-25'),
      'Episode 25',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1581'),
      'video-1581',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-39'),
      'Episode 39',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1477'),
      'video-1477',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-34'),
      'Episode 34',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1745'),
      'video-1745',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1482'),
      'video-1482',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-13'),
      'Episode 13',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-827'),
      'video-827',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-20'),
      'Episode 20',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1573'),
      'video-1573',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-22'),
      'Episode 22',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1592'),
      'video-1592',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-24'),
      'Episode 24',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-669'),
      'video-669',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-536'),
      'video-536',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-113'),
      'Episode 113',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-502'),
      'video-502',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-79'),
      'Episode 79',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-431'),
      'video-431',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-39'),
      'Episode 39',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-354'),
      'video-354',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-25'),
      'Episode 25',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-586'),
      'video-586',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-25'),
      'Episode 25',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613630045.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-206'),
      'video-206',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3964'),
      'video-3964',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-13'),
      'Episode 13 · Bolum 13',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1770136144.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3997'),
      'video-3997',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-174'),
      'Episode 174',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1774275943.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3940'),
      'video-3940',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-63'),
      'Episode 63 · Bolum 63',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1766508326.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3324'),
      'video-3324',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-26'),
      'Episode 26',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3475'),
      'video-3475',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-41'),
      'Episode 41',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1737391201.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3431'),
      'video-3431',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-177'),
      'Episode 177',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1735745456.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3575'),
      'video-3575',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-137'),
      'Episode 137',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1742731728.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3216'),
      'video-3216',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726646853.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3213'),
      'video-3213',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-118'),
      'Episode 118',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726411768.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2620'),
      'video-2620',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-26'),
      'Episode 26',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2601'),
      'video-2601',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-141'),
      'Episode 141',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1702912533.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2904'),
      'video-2904',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-105'),
      'Episode 105',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1714324762.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1072'),
      'video-1072',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-26'),
      'Episode 26',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1025'),
      'video-1025',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-70'),
      'Episode 70',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-235'),
      'video-235',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-26'),
      'Episode 26',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-125'),
      'video-125',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-45'),
      'Episode 45',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-32'),
      'video-32',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-32'),
      'Episode 32',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3802'),
      'video-3802',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-31'),
      'Episode 31',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2513'),
      'video-2513',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-59'),
      'Episode 59',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2860'),
      'video-2860',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-47'),
      'Episode 47',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713002910.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2413'),
      'video-2413',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1950'),
      'video-1950',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-26'),
      'Episode 26',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2141'),
      'video-2141',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-45'),
      'Episode 13 · Bolum 45',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2210'),
      'video-2210',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-74'),
      'Episode 74',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1902'),
      'video-1902',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-111'),
      'Episode 13 · Bolum 111',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1975'),
      'video-1975',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-44'),
      'Episode 17 · Bolum 44',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1922'),
      'video-1922',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-76'),
      'Episode 76',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1356'),
      'video-1356',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-26'),
      'Episode 26',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1598'),
      'video-1598',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-40'),
      'Episode 40',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1498'),
      'video-1498',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-35'),
      'Episode 35',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1758'),
      'video-1758',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1483'),
      'video-1483',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-13'),
      'Episode 13',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-828'),
      'video-828',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-21'),
      'Episode 21',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1574'),
      'video-1574',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-22'),
      'Episode 22',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1593'),
      'video-1593',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-24'),
      'Episode 24',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-670'),
      'video-670',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-537'),
      'video-537',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-114'),
      'Episode 114',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-503'),
      'video-503',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-80'),
      'Episode 80',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-432'),
      'video-432',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-40'),
      'Episode 40',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-355'),
      'video-355',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-26'),
      'Episode 26',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-603'),
      'video-603',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-26'),
      'Episode 26',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613630045.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-207'),
      'video-207',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-26'),
      'Episode 26',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3969'),
      'video-3969',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-14'),
      'Episode 14 · Bolum 14',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1770827662.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4002'),
      'video-4002',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-175'),
      'Episode 175',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1774802135.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3946'),
      'video-3946',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-64'),
      'Episode 64 · Bolum 64',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1767768929.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3392'),
      'video-3392',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-27'),
      'Episode 27',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3481'),
      'video-3481',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-42'),
      'Episode 42',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1737993095.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3478'),
      'video-3478',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-178'),
      'Episode 178',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1737560149.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3609'),
      'video-3609',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-138'),
      'Episode 138',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1743384414.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3221'),
      'video-3221',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1727422024.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3214'),
      'video-3214',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-119'),
      'Episode 119',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726412059.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2624'),
      'video-2624',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-27'),
      'Episode 27',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2602'),
      'video-2602',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-bolum-141'),
      'Bolum 141',
      5,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1702913626.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2919'),
      'video-2919',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-106'),
      'Episode 106',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1714931030.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1073'),
      'video-1073',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-27'),
      'Episode 27',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1026'),
      'video-1026',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-71'),
      'Episode 71',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-236'),
      'video-236',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-27'),
      'Episode 27',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-126'),
      'video-126',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-46'),
      'Episode 46',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-33'),
      'video-33',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-33'),
      'Episode 33',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3803'),
      'video-3803',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-32'),
      'Episode 32',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2514'),
      'video-2514',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-60'),
      'Episode 60',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2880'),
      'video-2880',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-48'),
      'Episode 48',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713575004.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2414'),
      'video-2414',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1953'),
      'video-1953',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-27'),
      'Episode 27',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2164'),
      'video-2164',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-46'),
      'Episode 14 · Bolum 46',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2224'),
      'video-2224',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-75'),
      'Episode 75',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1916'),
      'video-1916',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-112'),
      'Episode 14 · Bolum 112',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2024'),
      'video-2024',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-45'),
      'Episode 18 · Bolum 45',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1938'),
      'video-1938',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-77'),
      'Episode 77',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1359'),
      'video-1359',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-27'),
      'Episode 27',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1619'),
      'video-1619',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-41'),
      'Episode 41',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1521'),
      'video-1521',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-36'),
      'Episode 36',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1770'),
      'video-1770',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1504'),
      'video-1504',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-14'),
      'Episode 14',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-829'),
      'video-829',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-22'),
      'Episode 22',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1589'),
      'video-1589',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-23'),
      'Episode 23',
      3,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1609'),
      'video-1609',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-25'),
      'Episode 25',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-671'),
      'video-671',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-23'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-23-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1620192333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-538'),
      'video-538',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-18'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-18-episode-115'),
      'Episode 115',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-504'),
      'video-504',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-17'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-17-episode-81'),
      'Episode 81',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-433'),
      'video-433',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-16'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-16-episode-41'),
      'Episode 41',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613387473.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-356'),
      'video-356',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-10'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-10-episode-27'),
      'Episode 27',
      NULL,
      '{}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613383927.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-604'),
      'video-604',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-8'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-8-episode-27'),
      'Episode 27',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1613630045.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-208'),
      'video-208',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-7'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-7-episode-27'),
      'Episode 27',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612535417.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3970'),
      'video-3970',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-78'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-78-bolum-14'),
      'Episode 14 · Bolum 14',
      1,
      '{"English"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1770827923.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-4007'),
      'video-4007',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-77'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-77-episode-176'),
      'Episode 176',
      6,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1775409177.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3948'),
      'video-3948',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-76'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-76-bolum-65'),
      'Episode 65 · Bolum 65',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1768319004.jpg'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3393'),
      'video-3393',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-28'),
      'Episode 28',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3482'),
      'video-3482',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-71'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-71-episode-42'),
      'Episode 42',
      2,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1737993360.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3479'),
      'video-3479',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-70'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-70-episode-178'),
      'Episode 178',
      6,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1737561325.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3616'),
      'video-3616',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-69'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-69-episode-139'),
      'Episode 139',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      NULL,
      'https://play.niazitv.pk/images/episode_1744561514.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3233'),
      'video-3233',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-65'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-65-episode-28'),
      'Episode 28',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1728387791.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3217'),
      'video-3217',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-63'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-63-episode-120'),
      'Episode 120',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1726902576.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2625'),
      'video-2625',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-28'),
      'Episode 28',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703222099.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2610'),
      'video-2610',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-50'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-50-episode-142'),
      'Episode 142',
      5,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1703308378.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2937'),
      'video-2937',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-57'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-57-episode-107'),
      'Episode 107',
      4,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1715606462.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1074'),
      'video-1074',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-28'),
      'Episode 28',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1027'),
      'video-1027',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-72'),
      'Episode 72',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-237'),
      'video-237',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-28'),
      'Episode 28',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-127'),
      'video-127',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-3'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-3-episode-47'),
      'Episode 47',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1605545344.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-34'),
      'video-34',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-2'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-2-episode-34'),
      'Episode 34',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1604244480.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3804'),
      'video-3804',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-33'),
      'Episode 33',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2515'),
      'video-2515',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-53'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-53-episode-61'),
      'Episode 61',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1694880725.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2881'),
      'video-2881',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-52'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-52-episode-49'),
      'Episode 49',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1713575912.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2417'),
      'video-2417',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-48'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-48-episode-28'),
      'Episode 28',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1689509043.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1954'),
      'video-1954',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-28'),
      'Episode 28',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2165'),
      'video-2165',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-41'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-41-bolum-46'),
      'Episode 14 · Bolum 46',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671860399.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2293'),
      'video-2293',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-40'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-40-episode-76'),
      'Episode 76',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1667824028.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1930'),
      'video-1930',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-38'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-38-bolum-112'),
      'Episode 14 · Bolum 112',
      4,
      '{"English"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1664814333.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2025'),
      'video-2025',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-37'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-37-bolum-45'),
      'Episode 18 · Bolum 45',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1663665353.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1955'),
      'video-1955',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-36'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-36-episode-78'),
      'Episode 78',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1660049849.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1360'),
      'video-1360',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-28'),
      'Episode 28',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1631'),
      'video-1631',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-33'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-33-episode-42'),
      'Episode 42',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638711499.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1544'),
      'video-1544',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-31'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-31-episode-37'),
      'Episode 37',
      2,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638708551.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1806'),
      'video-1806',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-28'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-28-episode-28'),
      'Episode 28',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638677759.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1505'),
      'video-1505',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-27'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-27-episode-14'),
      'Episode 14',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638676629.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-830'),
      'video-830',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-23'),
      'Episode 23',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1590'),
      'video-1590',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-25'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-25-episode-23'),
      'Episode 23',
      3,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1632669643.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1610'),
      'video-1610',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-24'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-24-episode-25'),
      'Episode 25',
      1,
      '{"Urdu"}',
      'subtitled',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1631808953.webp'
    )
ON CONFLICT (source_id) DO UPDATE SET
  display_label = CASE WHEN video_variants.updated_at > video_variants.created_at THEN video_variants.display_label ELSE EXCLUDED.display_label END,
  languages = EXCLUDED.languages,
  version = EXCLUDED.version,
  thumbnail_url = EXCLUDED.thumbnail_url,
  publication_state = CASE WHEN video_variants.collection_id = extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:collection-68') THEN 'published' ELSE video_variants.publication_state END,
  updated_at = now();