INSERT INTO public.video_variants (id, source_id, collection_id, group_id, display_label, reported_season, languages, version, publication_state, duration_seconds, thumbnail_url)
VALUES
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2763'),
      'video-2763',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-91'),
      'Episode 91',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1137'),
      'video-1137',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-6'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-6-episode-91'),
      'Episode 91',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-999'),
      'video-999',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-5'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-5-episode-44'),
      'Episode 44',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1621820585.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-691'),
      'video-691',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-4'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-4-episode-91'),
      'Episode 91',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1612448555.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3867'),
      'video-3867',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-96'),
      'Episode 96',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2093'),
      'video-2093',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-91'),
      'Episode 91',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1550'),
      'video-1550',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-91'),
      'Episode 91',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-896'),
      'video-896',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-86'),
      'Episode 86',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3522'),
      'video-3522',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-92'),
      'Episode 92',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2766'),
      'video-2766',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-92'),
      'Episode 92',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3868'),
      'video-3868',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-97'),
      'Episode 97',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2097'),
      'video-2097',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-92'),
      'Episode 92',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1553'),
      'video-1553',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-92'),
      'Episode 92',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-897'),
      'video-897',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-87'),
      'Episode 87',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3523'),
      'video-3523',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-93'),
      'Episode 93',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2767'),
      'video-2767',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-93'),
      'Episode 93',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3869'),
      'video-3869',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-56'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-56-episode-98'),
      'Episode 98',
      1,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706598103.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2103'),
      'video-2103',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-93'),
      'Episode 93',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1556'),
      'video-1556',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-93'),
      'Episode 93',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-898'),
      'video-898',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-88'),
      'Episode 88',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3524'),
      'video-3524',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-94'),
      'Episode 94',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2771'),
      'video-2771',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-94'),
      'Episode 94',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2105'),
      'video-2105',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-94'),
      'Episode 94',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1559'),
      'video-1559',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-94'),
      'Episode 94',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-899'),
      'video-899',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-89'),
      'Episode 89',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3525'),
      'video-3525',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-95'),
      'Episode 95',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2774'),
      'video-2774',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-95'),
      'Episode 95',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2112'),
      'video-2112',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-95'),
      'Episode 95',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1560'),
      'video-1560',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-95'),
      'Episode 95',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-900'),
      'video-900',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-90'),
      'Episode 90',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3526'),
      'video-3526',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-96'),
      'Episode 96',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2775'),
      'video-2775',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-96'),
      'Episode 96',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2114'),
      'video-2114',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-96'),
      'Episode 96',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1562'),
      'video-1562',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-96'),
      'Episode 96',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-901'),
      'video-901',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-91'),
      'Episode 91',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3527'),
      'video-3527',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-97'),
      'Episode 97',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2778'),
      'video-2778',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-97'),
      'Episode 97',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2119'),
      'video-2119',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-97'),
      'Episode 97',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1565'),
      'video-1565',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-97'),
      'Episode 97',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-902'),
      'video-902',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-92'),
      'Episode 92',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3528'),
      'video-3528',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-98'),
      'Episode 98',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2780'),
      'video-2780',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-98'),
      'Episode 98',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2121'),
      'video-2121',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-98'),
      'Episode 98',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1569'),
      'video-1569',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-98'),
      'Episode 98',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-903'),
      'video-903',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-93'),
      'Episode 93',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3529'),
      'video-3529',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-99'),
      'Episode 99',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2782'),
      'video-2782',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-99'),
      'Episode 99',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2125'),
      'video-2125',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-99'),
      'Episode 99',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1572'),
      'video-1572',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-99'),
      'Episode 99',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-904'),
      'video-904',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-94'),
      'Episode 94',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3530'),
      'video-3530',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-100'),
      'Episode 100',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2786'),
      'video-2786',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-100'),
      'Episode 100',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2130'),
      'video-2130',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-100'),
      'Episode 100',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1575'),
      'video-1575',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-100'),
      'Episode 100',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-905'),
      'video-905',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-95'),
      'Episode 95',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3531'),
      'video-3531',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-101'),
      'Episode 101',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2788'),
      'video-2788',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-101'),
      'Episode 101',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2132'),
      'video-2132',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-101'),
      'Episode 101',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1577'),
      'video-1577',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-101'),
      'Episode 101',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-906'),
      'video-906',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-96'),
      'Episode 96',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3532'),
      'video-3532',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-102'),
      'Episode 102',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2791'),
      'video-2791',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-102'),
      'Episode 102',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2136'),
      'video-2136',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-102'),
      'Episode 102',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1578'),
      'video-1578',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-102'),
      'Episode 102',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-907'),
      'video-907',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-97'),
      'Episode 97',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3533'),
      'video-3533',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-103'),
      'Episode 103',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2793'),
      'video-2793',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-103'),
      'Episode 103',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2139'),
      'video-2139',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-103'),
      'Episode 103',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1580'),
      'video-1580',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-103'),
      'Episode 103',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-908'),
      'video-908',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-98'),
      'Episode 98',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3534'),
      'video-3534',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-104'),
      'Episode 104',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2795'),
      'video-2795',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-104'),
      'Episode 104',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2143'),
      'video-2143',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-104'),
      'Episode 104',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1582'),
      'video-1582',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-104'),
      'Episode 104',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-909'),
      'video-909',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-99'),
      'Episode 99',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3535'),
      'video-3535',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-105'),
      'Episode 105',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2796'),
      'video-2796',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-105'),
      'Episode 105',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2145'),
      'video-2145',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-105'),
      'Episode 105',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1585'),
      'video-1585',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-105'),
      'Episode 105',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-910'),
      'video-910',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-100'),
      'Episode 100',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3536'),
      'video-3536',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-106'),
      'Episode 106',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2798'),
      'video-2798',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-106'),
      'Episode 106',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2149'),
      'video-2149',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-106'),
      'Episode 106',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1588'),
      'video-1588',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-106'),
      'Episode 106',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-911'),
      'video-911',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-101'),
      'Episode 101',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3537'),
      'video-3537',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-107'),
      'Episode 107',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2801'),
      'video-2801',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-107'),
      'Episode 107',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2153'),
      'video-2153',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-107'),
      'Episode 107',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1591'),
      'video-1591',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-107'),
      'Episode 107',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-912'),
      'video-912',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-102'),
      'Episode 102',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3538'),
      'video-3538',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-108'),
      'Episode 108',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2804'),
      'video-2804',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-108'),
      'Episode 108',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2156'),
      'video-2156',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-108'),
      'Episode 108',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1594'),
      'video-1594',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-108'),
      'Episode 108',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-913'),
      'video-913',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-103'),
      'Episode 103',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3539'),
      'video-3539',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-109'),
      'Episode 109',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2807'),
      'video-2807',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-109'),
      'Episode 109',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2161'),
      'video-2161',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-109'),
      'Episode 109',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1595'),
      'video-1595',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-109'),
      'Episode 109',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-914'),
      'video-914',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-104'),
      'Episode 104',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3540'),
      'video-3540',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-110'),
      'Episode 110',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2808'),
      'video-2808',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-110'),
      'Episode 110',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2163'),
      'video-2163',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-110'),
      'Episode 110',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1597'),
      'video-1597',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-110'),
      'Episode 110',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-915'),
      'video-915',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-105'),
      'Episode 105',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3541'),
      'video-3541',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-111'),
      'Episode 111',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2811'),
      'video-2811',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-111'),
      'Episode 111',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2166'),
      'video-2166',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-111'),
      'Episode 111',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1599'),
      'video-1599',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-111'),
      'Episode 111',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-916'),
      'video-916',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-106'),
      'Episode 106',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3542'),
      'video-3542',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-112'),
      'Episode 112',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2812'),
      'video-2812',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-112'),
      'Episode 112',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2170'),
      'video-2170',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-112'),
      'Episode 112',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1602'),
      'video-1602',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-112'),
      'Episode 112',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-917'),
      'video-917',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-107'),
      'Episode 107',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3543'),
      'video-3543',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-113'),
      'Episode 113',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2815'),
      'video-2815',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-113'),
      'Episode 113',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2174'),
      'video-2174',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-113'),
      'Episode 113',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1606'),
      'video-1606',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-113'),
      'Episode 113',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-918'),
      'video-918',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-108'),
      'Episode 108',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3544'),
      'video-3544',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-114'),
      'Episode 114',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2820'),
      'video-2820',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-114'),
      'Episode 114',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2178'),
      'video-2178',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-114'),
      'Episode 114',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1608'),
      'video-1608',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-114'),
      'Episode 114',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-919'),
      'video-919',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-109'),
      'Episode 109',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3545'),
      'video-3545',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-115'),
      'Episode 115',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2821'),
      'video-2821',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-115'),
      'Episode 115',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2181'),
      'video-2181',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-115'),
      'Episode 115',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1611'),
      'video-1611',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-115'),
      'Episode 115',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-920'),
      'video-920',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-110'),
      'Episode 110',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3546'),
      'video-3546',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-116'),
      'Episode 116',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2824'),
      'video-2824',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-116'),
      'Episode 116',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2185'),
      'video-2185',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-116'),
      'Episode 116',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1612'),
      'video-1612',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-116'),
      'Episode 116',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-921'),
      'video-921',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-111'),
      'Episode 111',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3547'),
      'video-3547',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-117'),
      'Episode 117',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2825'),
      'video-2825',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-117'),
      'Episode 117',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2187'),
      'video-2187',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-117'),
      'Episode 117',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1613'),
      'video-1613',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-117'),
      'Episode 117',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-922'),
      'video-922',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-112'),
      'Episode 112',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3548'),
      'video-3548',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-118'),
      'Episode 118',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2826'),
      'video-2826',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-118'),
      'Episode 118',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2189'),
      'video-2189',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-118'),
      'Episode 118',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1614'),
      'video-1614',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-118'),
      'Episode 118',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-923'),
      'video-923',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-113'),
      'Episode 113',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3549'),
      'video-3549',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-119'),
      'Episode 119',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2829'),
      'video-2829',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-119'),
      'Episode 119',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2191'),
      'video-2191',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-119'),
      'Episode 119',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1617'),
      'video-1617',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-119'),
      'Episode 119',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-924'),
      'video-924',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-114'),
      'Episode 114',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3550'),
      'video-3550',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-120'),
      'Episode 120',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2831'),
      'video-2831',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-120'),
      'Episode 120',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2195'),
      'video-2195',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-120'),
      'Episode 120',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1621'),
      'video-1621',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-120'),
      'Episode 120',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-925'),
      'video-925',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-115'),
      'Episode 115',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3551'),
      'video-3551',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-121'),
      'Episode 121',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2836'),
      'video-2836',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-121'),
      'Episode 121',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2202'),
      'video-2202',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-121'),
      'Episode 121',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1624'),
      'video-1624',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-121'),
      'Episode 121',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-926'),
      'video-926',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-116'),
      'Episode 116',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3552'),
      'video-3552',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-122'),
      'Episode 122',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2837'),
      'video-2837',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-122'),
      'Episode 122',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2203'),
      'video-2203',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-122'),
      'Episode 122',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1627'),
      'video-1627',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-122'),
      'Episode 122',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-927'),
      'video-927',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-117'),
      'Episode 117',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3582'),
      'video-3582',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-123'),
      'Episode 123',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2840'),
      'video-2840',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-123'),
      'Episode 123',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2204'),
      'video-2204',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-123'),
      'Episode 123',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1628'),
      'video-1628',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-123'),
      'Episode 123',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-928'),
      'video-928',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-118'),
      'Episode 118',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3583'),
      'video-3583',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-124'),
      'Episode 124',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2842'),
      'video-2842',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-124'),
      'Episode 124',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2207'),
      'video-2207',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-124'),
      'Episode 124',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1629'),
      'video-1629',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-124'),
      'Episode 124',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-929'),
      'video-929',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-119'),
      'Episode 119',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3584'),
      'video-3584',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-125'),
      'Episode 125',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2843'),
      'video-2843',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-125'),
      'Episode 125',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2209'),
      'video-2209',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-125'),
      'Episode 125',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1630'),
      'video-1630',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-125'),
      'Episode 125',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-930'),
      'video-930',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-120'),
      'Episode 120',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3585'),
      'video-3585',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-126'),
      'Episode 126',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2844'),
      'video-2844',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-126'),
      'Episode 126',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2211'),
      'video-2211',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-126'),
      'Episode 126',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1634'),
      'video-1634',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-126'),
      'Episode 126',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-931'),
      'video-931',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-121'),
      'Episode 121',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3586'),
      'video-3586',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-127'),
      'Episode 127',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2845'),
      'video-2845',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-127'),
      'Episode 127',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2215'),
      'video-2215',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-127'),
      'Episode 127',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1637'),
      'video-1637',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-127'),
      'Episode 127',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-932'),
      'video-932',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-122'),
      'Episode 122',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3587'),
      'video-3587',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-128'),
      'Episode 128',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2850'),
      'video-2850',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-128'),
      'Episode 128',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2216'),
      'video-2216',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-128'),
      'Episode 128',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1641'),
      'video-1641',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-128'),
      'Episode 128',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-933'),
      'video-933',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-123'),
      'Episode 123',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-3588'),
      'video-3588',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-73'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-73-episode-129'),
      'Episode 129',
      6,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1729925112.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2854'),
      'video-2854',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-61'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-61-episode-129'),
      'Episode 129',
      5,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1706193682.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-2220'),
      'video-2220',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-43'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-43-episode-129'),
      'Episode 129',
      4,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1671202485.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-1644'),
      'video-1644',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-34'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-34-episode-129'),
      'Episode 129',
      3,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638977009.webp'
    ),
(
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'variant:' || 'video-934'),
      'video-934',
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:' || 'collection-26'),
      extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'group:' || 'collection-26-episode-124'),
      'Episode 124',
      2,
      '{"Urdu"}',
      'dubbed',
      'draft',
      2700,
      'https://play.niazitv.pk/images/episode_1638540439.webp'
    )
ON CONFLICT (source_id) DO UPDATE SET
  display_label = CASE WHEN video_variants.updated_at > video_variants.created_at THEN video_variants.display_label ELSE EXCLUDED.display_label END,
  languages = EXCLUDED.languages,
  version = EXCLUDED.version,
  thumbnail_url = EXCLUDED.thumbnail_url,
  publication_state = CASE WHEN video_variants.collection_id = extensions.uuid_generate_v5(extensions.uuid_ns_url(), 'collection:collection-68') THEN 'published' ELSE video_variants.publication_state END,
  updated_at = now();